### ISSUE TITLE
Another small bugg

### ISSUE THREAD

**Issue by livep2000** [andersevenrud/OS.js-v2#102]
At /src/javascript/handlers/example/handler.js

```javascript
self.onLogin(result.userData, function() 
```
Should be:

```javascript
self.onLogin(result, function() 
```

Else the logged on user is undefined

Imre

**Comment by MrSchism** [comment]
I'm not seeing that; I'm seeing result.userData on line 99.

**Comment by livep2000** [comment]
sorry, typo. you are absolute correct.

imre

**Comment by MrSchism** [comment]
Since JavaScript isn't my strongest language (that's actually why I took an interest in this; best way to learn is to dive in: sink or swim) does that change it to being okay or does the line still need to be changed?

**Comment by livep2000** [comment]
Well, I am writing a accounting system for the node server.
And took the example handler from the php based server.

Found a few other flaws also, be carefull!
The node server was marked with 'work in progress'.
Maybe the node server need to be altered,
instead the handler code.

imre

**Comment by MrSchism** [comment]
The Node server is still very much a work in progress.

**Comment by MrSchism** [comment]
From what I can tell, the Node server is still very much an unstable work-in-progress.

@andersevenrud should this bit of code be changed or is it more of a server issue?

**Comment by andersevenrud** [comment]
@MrSchism 
I just see change X to Y without reasoning. I think he has an error in his implementation because the code seems correct:

- https://github.com/andersevenrud/OS.js-v2/blob/master/src/server-php/handlers/example/handler.php#L71
- https://github.com/andersevenrud/OS.js-v2/blob/master/src/javascript/handlers/example/handler.js#L99

**Comment by livep2000** [comment]
Confirmed that the code is correct.

In the php server is becomes clear that login returns an Object (as json)

result.userSettings
result.userData

In the lacking example handler for node I returned only userData.

Imre

**Comment by andersevenrud** [comment]
Yes, there is not an example node handler (yet). I've been working on this entirely alone and I guess I forgot it :/ I will make one

**Comment by andersevenrud** [comment]
This issue is continued here: #11
