### ISSUE TITLE
doSetLocale(l) receives wrong format

### ISSUE THREAD

**Issue by livep2000** [andersevenrud/OS.js-v2#104]
Morning, 

(in OS.js-v2/src/javascript/api.js, line 244)

Sorry to be the little PITA. :)

String l in this function receives the value 'nl'.
It wants 'nl_NL' and switches to default locale. ( en_EN ) 

To proof this is the case, did a dirty patch:
```javascript
l = l + "_" + l.toUpperCase();
```

Wich is working. I think the OSjs.API.getLocale should return the proper format?

Imre

**Comment by andersevenrud** [comment]
@livep2000 

This was actually solved by fixing up the global locale getter function. Thanks :)

https://github.com/andersevenrud/OS.js-v2/blob/master/src/javascript/utils.js#L450

**Comment by livep2000** [comment]
Thanks to you, my customers now read Dutch :)
