### ISSUE TITLE
Dead symbolic link in dist-dev

### ISSUE THREAD

**Issue by livep2000** [andersevenrud/OS.js-v2#106]
In dist-dev there is an config.js linking to nothing.

Sorry for posting such a minor issue.

Imre

Addition: Am i right: in dist-dev the symbolic links to osjs.css and osjs.js are missing ?

**Comment by andersevenrud** [comment]
You're right. Missed that one :)

**Comment by andersevenrud** [comment]
Addition: Am i right: in dist-dev the symbolic links to osjs.css and osjs.js are missing ?

These are missing because you have not run `grunt core`
