### ISSUE TITLE
Autosave settings.

### ISSUE THREAD

**Issue by livep2000** [andersevenrud/OS.js-v2#107]
If navigating away from the page without logging out:

Usersettings are lost. 
Is it possible to save just before closing? Becease accidental navigating away happens very easy. (Browsing usually not involve saving your work)

imre

**Comment by andersevenrud** [comment]
Since you cannot reliably do asyncronous calls when a page unloads (they get cancelled), no.

But you can interrupt it and show a warning message with yes/no button. Ex: "Are you sure you want to quit? All unsaved settings and applications data will be lost"

**Comment by livep2000** [comment]
Thought so..... When interupting is reliable,
the question could be ''wanne save your session?'

Imre

**Comment by andersevenrud** [comment]
As I said, you cannot do asyncronous calls on page unload. It cannot ask you to save the session. It would have to warn you that you will loose it if not clicking "Cancel" and quit properly (with the log out button).

**Comment by andersevenrud** [comment]
@livep2000

How to enable warning message.

- Alternative 1: Set `ShowQuitWarning` to `true` in *src/conf/110-frontend.json* (not recommended as this file might be overwritten by updates)
- Alternative 2: Set up a custom config, example *src/conf/999-custom.json* with:
```

{
  "settings" : {
    "frontend" : {
      "Core" : {
        "ShowQuitWarning":  true
      }
   }
}

```

Then run `grunt config` and restart OS.js. You should now see an error when closing/reloading without using the Quit button.
