### ISSUE TITLE
Install a zip from shared folder not working

### ISSUE THREAD

**Issue by livep2000** [andersevenrud/OS.js-v2#108]
Install a zip file from a home folder works perfectly.

But not from te shared folder. The packages.json is not updated and in the packages folder
an incorrect structure apears, like:

home:// packages/chat/chat/<package files>

If installed from the homefolder itself or the test from the store its is like this:

home:// packages/chat/<package files>

Imre

**Comment by andersevenrud** [comment]
Have you simply thought of not having a root dir in the zip ? ;)

**Comment by andersevenrud** [comment]
Oh, now I understand. I will have a look

**Comment by livep2000** [comment]
Using zip.js, maybe important beceause i saw that Java is an option too.

Imre

**Comment by livep2000** [comment]
Sorry, found more inconsistent behaviour.

Reproduce:
1. Wipe my home folder.
2. Wipe my settings & groups data from the mysql table.
3. Login with the php handler.

What happens:
1. The handler is creating the home folder.
2. In the javascript console this error:
FShome:///Packages/packages.json 404 (Not Found)

Now install test from your resopitory:
3. Test is not to find in the menu or the process viewer.
4. Homefolder looks like this:

home:// 
file: test:zip
folder : Packages with empty file packages.json.

Some suggestions:

1. Create a folder 'packages' in the home folder at first logon.
2. Hide that folder from VFS. (Hey, hidden folder function?)
3. Install the user level applications there.
4. Missing : cannot find a way to remove user packages.

Imre

**Comment by andersevenrud** [comment]
So, basically, the problem is that the "Packages" folder is missing ?!

> Hide that folder from VFS. (Hey, hidden folder function?)

Why hide it ? :)

> Missing : cannot find a way to remove user packages.

Deleting the folder will suffice, but yeah, an uninstall button makes sense.

**Comment by livep2000** [comment]
Hey Anders,

Hidden user packages and 'uninstall' user packages.

Try to look at it from a real-live production enviroment.
I, as the owner of a website want to give the users what they need. (What i think they need)

For example a read only folder with custom packages, the user can install and use, or remove as they want so.

Users, if you got more then a few, do dumb things, like removing files belonging to a package.
For them only the package function is important.

Is this never ment for multi user purpose?

Imaging how many mails ..... :) 

"So, basically, the problem is that the "Packages" folder is missing ?!"

No, i'll tried to cover that by creating it, and also an empty packages.json.

In the case of the test.zip from the store:

test.zip is placed in the root, unpacked and uninstalled.

Sorry when iám no fully clear :(

Imre

**Comment by andersevenrud** [comment]
> Is this never ment for multi user purpose?

Yes, it is.

> For example a read only folder with custom packages, the user can install and use, or remove as they want so.

Read-only will not allow you to install any packages. I don't think turning it off/on when installing/uninistalling is a good idea... it pretty much defeats the purpose and will lead to more potential errors.

> Users, if you got more then a few, do dumb things, like removing files belonging to a package.

I could make the packages folder a dotfile and add a warning if you try to remove/modify any files.

> No, i'll tried to cover that by creating it, and also an empty packages.json. In the case of the test.zip from the store: test.zip is placed in the root, unpacked and uninstalled.

I still don't understand what you mean. I have to check this out myself.

**Comment by livep2000** [comment]
Yes, I understand the complexity with all of this. Going to try te be more clear.

A read only folder:

A folder that can hold things like uninstalled packages, wallpappers to choose from, etc.
If a user want to install, the package it is installed in a hidden folder inside the home.

On this way, the owner of the site can provide optional functions to the users. The codemirror package for example will be very interessing for programming related websites, but not at all for something about cars.

So, why installed in the home folder at all?

Beceause they are 'per user' installed. If a user is deleted, the folder with the data is also gone.

"I still don't understand what you mean. I have to check this out myself."

Going to repreduce this again, and try yo describe it in more detail.

Imre

**Comment by livep2000** [comment]
Test 1: Installing Test.zip from the "App store".
Result: May'be it was ment this way, de Test.zip is copied to the home folder and can be installed frome there.

Test 2: Installing a package from the home folder. Copied "RTCGroupVideo.zip" into the folder.
Result: Works great !

Test 3: Install from 'shared' folder. Copied "Chat.zip" into the folder.
Result: Complete confusion, WTF, this is working also!!!!

Don't understand, did about 20 tests yesterday.

Sorry.

**Comment by andersevenrud** [comment]
> A folder that can hold things like uninstalled packages, wallpappers to choose from, etc. If a user want to install, the package it is installed in a hidden folder inside the home.

Then a simple *dotfile* would suffice :)

> On this way, the owner of the site can provide optional functions to the users. The codemirror package for example will be very interessing for programming related websites, but not at all for something about cars.

I have a much easier way of solving this. I'll just add a "EnabledPackages" array to the user settings storage and add toggles in the "Settings" application. This will simply hold a list of system installed packages you want to use (By default is empty, which means "all").

Also, this can be solved with the recent implementation of groups!

> Beceause they are 'per user' installed. If a user is deleted, the folder with the data is also gone.

Having all of these packages installed per user will take up insane amounts of space (depending on how many there are). Kind of redundant if you ask me, hence the suggestion above.

Well, techincally there is no "data" stored inside an actual application folder. But if it's settings you talk about I can make an API method to clear them on a specific application (and maybe implement this in the uninstall process)

**Comment by andersevenrud** [comment]
Well... Glad to see it works. But if you had problems with this, it might be intermittent. Keep a look out for it again. I will also try to reproduce it :)

**Comment by andersevenrud** [comment]
I just added some of the things that came up here in #49. Feel free to comment there if I missed something
