### ISSUE TITLE
[Server] Node.js Server

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#11]
Some features are still missing from the Node.js backend:

- [x] Add User/Sessions in Core API
- [x] Core Extension via config
- [x] Add missing "curl" API call support
- [x] Needs a cleanup
- [x] Add the same VFS security checks as in PHP server
- [x] Needs "example" handler
- [x]  Buffered file downloads/reads

**Comment by junland** [comment]
I know it #34 you were discussing using ws over socket.io, I found this article that might be of some use. https://medium.com/@denizozger/finding-the-right-node-js-websocket-implementation-b63bfca0539

**Comment by andersevenrud** [comment]
I will open a separate issue for security based issues -- closing this
