### ISSUE TITLE
Get error when want to open Drum Sampler v0.6.

### ISSUE THREAD

**Issue by Subhajit-Sarkar** [andersevenrud/OS.js-v2#117]
Summary:
Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it

Trace:
Error: Failed to execute 'decodeAudioData' on 'AudioContext': invalid ArrayBuffer for audioData.
at Error (native)
at http://osjsv2.0o.no/packages/experiments/DrumSampler/combined.js:313:19
at Object.Utils.ajax.onerror (http://osjsv2.0o.no/osjs.js:5225:13)
at XMLHttpRequest.request.onerror (http://osjsv2.0o.no/osjs.js:765:16)

**Comment by andersevenrud** [comment]
What kind of browser were you running ? It seems a very few have this problem

**Comment by Subhajit-Sarkar** [comment]
Google Chrome.

**Comment by andersevenrud** [comment]
I'm running the exact same versions as you, but not getting an error. I'm suspecting it is a problem with a file transfer and/or my server configuration. I will have a look at this. Thanks for reporting :)

**Comment by Subhajit-Sarkar** [comment]
Thank you for your kind information.
