### ISSUE TITLE
Webhost/Custom URI deployment support

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#118]
Currently, installing OS.js to a webhost can be a bitch.

**In latest commit this has been adressed, but not finished**

- [x] Building of custom htaccess files
- [x] Auto-detect path in VFS
- [x] Configurable server-path via config
- [x] Package Manifest needs to make use of configurable path
- [x] Fix /blank.css errors
- [x] Auto-detect path in frontend instead of using custom uri in config ?!
- [ ] Look into global variables for htaccess files instead of generating with a static string

**Simply build on your system and copy over via FTP or whatever**

Instructions: https://github.com/andersevenrud/OS.js-v2/blob/master/INSTALL.md#webhost

**Comment by andersevenrud** [comment]
@khoaakt I've made it so you can build OS.js for running on a server like you did. It is now very simple and requires only a few steps :)

https://github.com/andersevenrud/OS.js-v2/blob/master/INSTALL.md#webhost

**Comment by khoaakt** [comment]
yeah, it's very simple :). GJ @andersevenrud .
But if i want update os.js build then what i do? Copy what folders and files?

**Comment by andersevenrud** [comment]
@khoaakt Rebuild and copy changed files.

**Comment by andersevenrud** [comment]
@khoaakt I just commited a fix for the problem you were having with reading files.

**Comment by andersevenrud** [comment]
Closing this for now since it basically works fine. I don't think the last task is actually achievable
