### ISSUE TITLE
Chrome - can't drag windows.

### ISSUE THREAD

**Issue by ComputeLinux** [andersevenrud/OS.js-v2#119]
Happens on both windows and ubuntu.

**Comment by andersevenrud** [comment]
Thanks for reporting!

I think this is related to #112. Do you have a touch screen ?

**Comment by ComputeLinux** [comment]
Yes, but I am not using it to move the windows.

**Comment by staticextasy** [comment]
It is not related to the physical usage of the touchscreen.

**Comment by ComputeLinux** [comment]
Ok, let me disable the driver

**Comment by ComputeLinux** [comment]
By the way, this isn't specifc to W8. Running Ubuntu on real HW right now, it still happens. So it's a chrome only thing.

**Comment by andersevenrud** [comment]
I just committed 9f0bd9e9363979091d1033def1c88704c7d56ec4 to rework touch detection. Demo has also been updated and rebuilt. Can you test again ? :)

**Comment by ComputeLinux** [comment]
Fixed, thanks!

**Comment by staticextasy** [comment]
Im guessing touch or not, chrome handles clicks and touches weirdly.

**Comment by ComputeLinux** [comment]
yea, happened on my non touch computer too.

**Comment by andersevenrud** [comment]
The thing is, touch-detection is pretty much broken now. There is no safe/reliable way to do it in javascript :/ So now I'm only enabling touch input if the device is matching ios/android/blackberry etc.

**Comment by staticextasy** [comment]
When i discovered the original bug i was not on a touch device either.

**Comment by andersevenrud** [comment]
Broken because browser vendors implements this differently. It seems latest update breaks it even further. Previously this was only a problem on Windows 8.x, but now spans all platforms.

**Comment by staticextasy** [comment]
Is this a JS specific issue only? Could we use a wrapper from something else to handle touch detection

**Comment by andersevenrud** [comment]
I would not have detected this, so thank you very much!

**Comment by andersevenrud** [comment]
@staticextasy I'll need to just ignore detection all together and just *assume* every device is a touch-screen and rewrite event-binding. That's the only way AFAIK.

**Comment by ComputeLinux** [comment]
This is chrome only so I'm guessing blink. Maybe detect if it's a non blink/webkit browser then do touch detection?

**Comment by staticextasy** [comment]
Sounda like a good time.

**Comment by andersevenrud** [comment]
@ComputeLinux I will have to look at what Modernizer etc. does with this problem. Browser-detection is wonky and a bit hacky... but it might be the only way.

Already it's pretty ugly: https://github.com/andersevenrud/OS.js-v2/blob/master/src/javascript/utils.js#L414

Interesting reads:
- http://www.stucox.com/blog/you-cant-detect-a-touchscreen/
- http://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript

**Comment by andersevenrud** [comment]
Also: https://github.com/Modernizr/Modernizr/issues/548
