### ISSUE TITLE
[API] Email Client, Calendar and Account Sync

### ISSUE THREAD

**Issue by rubengc** [andersevenrud/OS.js-v2#121]
Two of the most important enterprise-class applications are an email client and a calendar with events support

Additionally, an account sync functionality where with one sync you can get access to all your content (emails, calendar events, contacts, cloud drives, online docs, etc) will be really good

**External repo** https://github.com/andersevenrud/OS.js-v2-office . Just clone and rebuild configs+manifest.

- [x] Create AccountManager wrapper class
- [x] Create Account abstraction class
- [x] Account data storage (VFS)
- [ ] Settings and state storage

- Synchronization method
  - [x] Google read
  - [ ] Google write
  - [ ] Microsoft read
  - [ ] Microsoft write

- Applications
  - [ ] Email
  - [ ] Calendar
  - [ ] Contacts
  - [x] GoogleMail
  - [x] GoogleContacts
  - [ ] GoogleCalendar

Google versions of these applications live in *extras* repo

**Comment by andersevenrud** [comment]
I started on this, but never got to finish it. I will look into this when my vacation starts.... I have way to much work to do right now :/

**Comment by rubengc** [comment]
Ah, a comand line app to execute OSjs and native commands will be useful too

an awesome theme can be this http://andersevenrud.github.io/shell/ xD

**Comment by andersevenrud** [comment]
> Ah, a comand line app to execute OSjs and native commands will be useful too


I actually have one, but I don't see the use for it... hence it's not included anywhere. It's so much better to just open the developer console in the browser :p 

But I do want to add a real terminal emulator with buffers and all that so you can SSH and other sweet stuff like that. There are quite a few good libraries out there.

**Comment by andersevenrud** [comment]
@rubengc I have started on an *account manager* that will allow you to add accounts etc. much like you do on smartphones etc.

That is just the beginning of it all though. Still needs a proper Calendar and Email app.

**Comment by rubengc** [comment]
@andersevenrud That's sound really good!!!

I will wait impatiently for the results

**Comment by andersevenrud** [comment]
@rubengc I think I have something going here now. The library can now read feeds from online services (in this example contacts). Next would be to create write/modification support and hook it up to the synchronization process.

![Screenshot of progress](http://i.imgur.com/zVxuvWc.png)

**Comment by andersevenrud** [comment]
@rubengc Have gotten some work done on the calendar implementation. If you have any UI design in mind for this, please let me know :)

Actuall notification and syncing of the events are in progress too!

![Screenshot of calendar progress](http://i.imgur.com/ac4JZAb.png)

**Comment by andersevenrud** [comment]
@rubengc Just letting you know there is also some good progress on the Email application. You can now list folders and messages, send and recieve messages, download attachments (so far only for Google and no cache has been created).

It is also integrated with the Contacts application.

![Screenshot of email progress](http://i.imgur.com/hpF74Tq.png)

**Comment by andersevenrud** [comment]
@rubengc Just thought I'd give you an update.

I have now moved *Google Contacts* and *Google Mail* clients into the **extras** repository. They are considered "usable" by now.

Mail application is only missing a few minor functions (mainly sending of attachments). The contacts is only missing midification/adding of entries.

I will look at making abstractions (to make it work with, ex. Outlook) for this after a little break. I've been on a week coding binge now and feeling a bit tired :p

![Latest screenshot](http://i.imgur.com/xSJ6Rn1.png)

**Comment by junland** [comment]
Looks good. @andersevenrud Don't burn yourself out, take a little rest for a day or two. :)

**Comment by andersevenrud** [comment]
@junland I'll try ;)

**Comment by andersevenrud** [comment]
Now that the Google versions of these client applications are coming along nicely, I will merge this with #15, since this all will be a feature of the official release branch :)

**Comment by oxeron** [comment]
Hello @andersevenrud , is the calendar view available in the project ?

**Comment by andersevenrud** [comment]
Hi @oxeron .

Currently there is no calendar component, no.

**Comment by oxeron** [comment]
Is it in your plan for the future or do you think it could be easily done with a https://fullcalendar.io integration maybe ?

**Comment by andersevenrud** [comment]
@oxeron Yeah, it could be done with that library, but I am trying to avoid using jQuery (and things like that). But I'm sure there are lots of alternatives out there.

It would definitely be nice to have such a thing, so I will look around. Maybe you could do that too ? :)
