### ISSUE TITLE
Lightweight Development Appliance

### ISSUE THREAD

**Issue by MrSchism** [andersevenrud/OS.js-v2#123]
I've been quiet recently, largely because I've been dumping time into another project I stumbled upon: a cross-platform QEMU/TinyCore-based VM that can be found over at https://github.com/miklevin/levinux/

It'd be nice to have a custom version of that rolled for OS.js as a fast way to download and develop.

The total OS/QEMU size is around 25 MB.  It really swells up once OS.js-v2 is installed (due to git history and whatnot).  I'm in the process of just getting OS.js installed on it.  All of the packages are available, but I've run into a couple issues which I'll document next time I come across them.

**Comment by andersevenrud** [comment]
Sorry, but I'm having a rough time understanding this. You mean running OS.js as a [web]server inside the virtual machine ?

**Comment by MrSchism** [comment]
Essentially, set up OS.js entirely within the virtual machine so all a developer has to do is download the VM and run it and they have instant access to their own, functional OS.js environment.  I suggested the one above because it doesn't require installation or admin rights on the host OS (which is why I've been spending some time on it).

**Comment by andersevenrud** [comment]
Aha. Someone actually provided a Vagrant-file which is essentially the same thing :)

(you just have to download that file and "start" it in Vagrant app)

https://github.com/andersevenrud/OS.js-v2/blob/master/INSTALL.md#vargant

https://github.com/andersevenrud/OS.js-v2/blob/master/Vagrantfile

https://www.vagrantup.com/

**Comment by andersevenrud** [comment]
I just realized I have a spelling error there

**Comment by andersevenrud** [comment]
But again, Vagrant will install an entire linux distro that is much larger, so this might be more attractive ;)

**Comment by MrSchism** [comment]
Exactly...Well, this does too... the distro is just 9mb. This is downloaded and requires zero installation or configuration on the host OS... and no admin requirements.

Literally just download or clone (if you clone, copy to another directory).  It'd make testing packages faster for a few people.  Trick will be setting up git/gitignore to leave the host and only dev OSjs.

**Comment by MrSchism** [comment]
During setup, while following the manual install method:
```
tc@box:~/OS.js-v2-master$ ./bin/start-node-dist.sh
module.js:338
    throw err;
          ^
Error: Cannot find module 'node-fs-extra'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/tc/OS.js-v2-master/src/server-node/server.js:36
1:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

I'm going to spin up another VM and just try the automatic install script and see how it goes.

**Comment by andersevenrud** [comment]
@MrSchism Looks like you have not installed the dependencies `npm install`

**Comment by MrSchism** [comment]
I'll be giving it another shot later this evening while documenting what I do in a step-by-step process.

**Comment by andersevenrud** [comment]
@MrSchism Nice :)

**Comment by andersevenrud** [comment]
@MrSchism Any luck getting it going ? ;)

**Comment by andersevenrud** [comment]
@MrSchism I'm closing the issue because of inactivity. Feel free to resume it if there are any updates!

**Comment by MrSchism** [comment]
I was giving it a shot, but not getting anywhere.  I think the qemu was suffering major performance issues.  It locked up installing, but I was on my netbook.  I'll try again on my desktop and see how it goes.
