### ISSUE TITLE
Clicking "Cancel" on the logout confirmation dialog still logs out

### ISSUE THREAD

**Issue by NathanCJohnson** [andersevenrud/OS.js-v2#124]
This might just be an issue on the public demo, but just wanted to make you guys aware of this.

**Comment by andersevenrud** [comment]
Maybe I should add another button :)

It should be like: Yes, No and Cancel.

Sorry about the confusion. Will fix!

**Comment by NathanCJohnson** [comment]
No problem, what would be the difference between the "No" and "Cancel" buttons?

**Comment by NathanCJohnson** [comment]
Oh, nevermind, I see. The dialog asks if you want to save the session. That makes sense now. Another button would definitely help :P

**Comment by andersevenrud** [comment]
Will add another button ASAP :)

**Comment by NathanCJohnson** [comment]
Alright, cool :)

I have to say, OS.js is quite amazing. Great job on it!

**Comment by andersevenrud** [comment]
Well, thank you :)

Den søndag 28. juni 2015 skrev Nathan Johnson <notifications@github.com>
følgende:

> Alright, cool :)
>
> I have to say, OS.js is quite amazing. Great job on it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersevenrud/OS.js-v2/issues/124#issuecomment-116181406>
> .
>


-- 

Anders F. Evenrud
Software Developer

Blog: http://tinyurl.com/cjfrfx8

**Comment by andersevenrud** [comment]
@NathanCJohnson Fixed so it now gives you the option of **yes**, **no** and **cancel**. Maybe that makes it clearer :)

**Comment by NathanCJohnson** [comment]
Awesome! Yeah that is a lot clearer :)
