### ISSUE TITLE
Installation of libraries in the OS

### ISSUE THREAD

**Issue by rubengc** [andersevenrud/OS.js-v2#125]
In any operating system you need to install libraries for your developments (and your users also need to have installed these libraries) such as Java or C++

In OSjs libraries needed are javascript, css and php as jQuery, Bootstrap or TCPDF, respectively

It would be very nice to install these libraries from the store (or by command line), and when someone downloads and app, the system detects what libraries needs and download all of them

This aspect will be atractive for all developers that want to develop under OSjs

**Comment by andersevenrud** [comment]
The thing is applications ("packages") live in their own git-repository and have a package.json. That is how dependencies are managed. You use "npm" and "git submodules".

When you start an app in OS.js it will first check the dependencies are loaded (via the provided list in app metadata), if not it will go ahead and do so. It is the package developers responsibility to have everything required to go from there on.

> It would be very nice to install these libraries from the store (or by command line)

Command line is how it is for now. OS.js does not have any platform spesific GUI utilities at the moment.

You just download the package, and on the server-side run "npm install" etc. to download all the libraries, dependencies or whatever you have.

> This aspect will be atractive for all developers that want to develop under OSjs

That is what my main goal is overall. I'm using all of the mainstream developer tools out there: node, npm, grunt, less-css and a *very* modular prototype based javascript API. So it should not be hard for anyone having at least some knowledge of these tools to get started. I also provide full documentation at http://os.js.org/doc/¨

:)

**Comment by andersevenrud** [comment]
I forgot: Store applications come as archives and are intended to run fully out of the box. Just like Firefox Marketplace and smartphone apps. So these include all the libraries and dependencies required.

If you install them manually from a repo (with full source, docs etc), you have to use the command line to set up the libs/deps... but again is fully automatic with "npm" (and/or "grunt").

**Comment by andersevenrud** [comment]
@rubengc I forgot to mention another thing. There is a package type of "extension" that you can use to include libraries and other extensions.

Example: http://os.js.org/doc/manuals/man-broadway.html

This loads a library and hooks up API functions for OS.js (library)

**Comment by andersevenrud** [comment]
I am closing this. If you have any further questions, please post them in #49

**Comment by khoaakt** [comment]
I think like @rubengc . Someones won't know what package is missing. Example is download the OS.js-v2-expermiments package. It required some js like zip.js; three.js; ... etc. At the first time i download them, grunt had error because missing packages and i has embarrassed when catch that error :sob:

**Comment by andersevenrud** [comment]
@khoaakt You got that error because you did not use git with recursive clone. If you follow the documentation it will set up all libraries/dependencies for you :) "experiments" is not a package, but a repository *with* packages. To manage third party stuff automatically I went for *git submodules* for OS.js package repositories (which is something entirely different than a zip or store application)

http://os.js.org/doc/manuals/man-package-manager.html

**Comment by khoaakt** [comment]
why it is always in http://os.js.org/doc/manuals but did I not know it? :scream:

**Comment by andersevenrud** [comment]
@khoaakt All documentation is on the homepage.

Manuals: http://os.js.org/doc/manuals/
Tutorials: http://os.js.org/doc/tutorials/
API: http://os.js.org/doc/client/
