### ISSUE TITLE
Manual Install Error

### ISSUE THREAD

**Issue by junland** [andersevenrud/OS.js-v2#126]
Was going to try to run this on a Ubuntu VM however I came across this when running the start up script.
````
ubuntu@ubuntu-amd64:~/OS.js-v2/bin$ ./start-node-dev.sh
module.js:340
    throw err;
          ^
Error: Cannot find module '/home/ubuntu/OS.js-v2/bin/src/server-node/server.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
````

All I did was follow the "Manual Install" procedures and I installed the legacy nodejs package and ran the start script in the bin directory...

**Comment by andersevenrud** [comment]
That is because you are running it from the wrong directory.

You have to be in the root folder then run "./bin/start-node-dev.sh" :)

**Comment by junland** [comment]
Ahhhh Okay thanks!
