### ISSUE TITLE
[API] TCP over Web support

### ISSUE THREAD

**Issue by hiccup01** [andersevenrud/OS.js-v2#127]
OS.js is great but adding TCP would even greaten the possiblities (HTTP(S), VNC, SSH etc.) check this out to learn more:http://artemyankov.com/tcp-client-for-browsers/

**Comment by andersevenrud** [comment]
@hiccup01 I actually have a TCP/IP wrapper that runs on websocket that works similar to this. I just never added it to OS.js because I considered it very experimental. I'm going to look more into this. Thanks!

**Comment by andersevenrud** [comment]
I will add support for WebTCP.

Doing a cleanup, so this will be merged with #49 for the time being because it will be a part of the *extras* repository.
