### ISSUE TITLE
[Service] Developer Service

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#133]
This is a background service intended for developers.

*Functions are available through an icon on the panel. Only works with dist-dev*

- [x] Reloading of Manifest
- [x] dist-dev manifest with mtime
- [x] Detect mtime changes on packages
- [ ] Re-launching of applications upon change
- [ ] Re-launch session upon core changes

**Comment by andersevenrud** [comment]
@junland :)

**Comment by junland** [comment]
:+1:

**Comment by andersevenrud** [comment]
This will automatically resolve itself after #136 -- All the reloading functions will be in options.

"patching" is a part of the new update
