### ISSUE TITLE
Core Translations

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#14]
OS.js is lacking in the Translation department. There is a separate issue for Applications: #18 

[Full instructions on Wiki](https://github.com/andersevenrud/OS.js-v2/wiki/Join-the-translation-team)

**NEEDS UPDATE AFTER 1 JAN 2015**

## In progress

- [x] English (en_EN)
- [x] Norwegian (no_NO) @andersevenrud
- [x] German (de_DE) @danielang
- [x] French (fr_FR) @emersion
- [x] Russian (ru_RU) @Fabel 
- [x] Chinese (ch_CN) @zqqq
- [x] Dutch (nl_NL) Imre Biacsics
- [x] Polish (pl_PL) @michal4132
- [x] Vietnamese (vi_VN) @khoaakt

## Awaiting

- [ ] Hindi - India (hi_IN) @MrSchism 
- [ ] Spanish - Puerto Rico (es_PR) @MrSchism 

## Looking for

- [ ] Spanish (es_ES)
- [ ] Danish (dn_DN)
- [ ] Swedish (se_SE)
- [ ] Finnish (fi_FI)

... and more

**Comment by andersevenrud** [comment]
Merged with #18

**Comment by Malte0621** [comment]
I'm new to github stuff, i didn't notice this post. But i translated the core to Swedish.
(I dunno if it helps, but i hope so. It will most likely help my friends 👍 )
