### ISSUE TITLE
EXTREME: Inapropriate content on demo server

### ISSUE THREAD

**Issue by ComputeLinux** [andersevenrud/OS.js-v2#142]
shared/
Has, let's just say inappropriate content.

**Comment by andersevenrud** [comment]
Haha. Yeah! This is a known problem. Before capping the upload limit it was used as a filesharing service. The server is on a 100Mbit connection, so it is a nice way to share stuff :P 

Was there more than just the `porn` folder ? I deleted that one at least

**Comment by ComputeLinux** [comment]
Possibly put a filter on names of files/folders?

**Comment by ComputeLinux** [comment]
Also, yes there was a i_made_a_penis_enjoy.odraw.

**Comment by ComputeLinux** [comment]
fuck this earth.txt

**Comment by MrSchism** [comment]
Putting a filter on will just result in people bypassing names.  Most of what was in /shared/porn was random character files.

I still think a cron-job to clear the folder every night would be a good idea.

**Comment by ComputeLinux** [comment]
That's actually a pretty good idea @MrSchism

**Comment by MrSchism** [comment]
It was discussed on #85.

**Comment by andersevenrud** [comment]
If someone is up for some coding, let me know! I'd really like to have a scrubber going in a cron :)

**Comment by ComputeLinux** [comment]
Where is the /shared folder even stored?

**Comment by andersevenrud** [comment]
> Where is the /shared folder even stored?

`./vfs/public`

**Comment by MrSchism** [comment]
@andersevenrud What about the /home folder?

**Comment by andersevenrud** [comment]
`./vfs/home/demo` for the demo server
