### ISSUE TITLE
Low Importance: Double click to maximize window

### ISSUE THREAD

**Issue by ComputeLinux** [andersevenrud/OS.js-v2#143]
This. Everything ever does it.

**Comment by andersevenrud** [comment]
This never came to mind! I'll add that in the new branch #136 :)

**Comment by ComputeLinux** [comment]
Thanks! I'll close this now!

**Comment by andersevenrud** [comment]
Added in commit ab90805fb67460034ce328703215858673b895cc :)

Will be a part of the next merge!
