### ISSUE TITLE
[Core] Settings rewrite and misc cleanups

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#149]
@RyanRiffle Initiated this. And I feel the same way as he does.

The settings integration is way to abstract and hops through many hoops before actually doing anything.

A singleon instance or something similar would be much better that does not bind with Window and Application classes, but rather accessed with a static method.

~~**Branch**: https://github.com/andersevenrud/OS.js-v2/tree/new-settings~~

**MERGED INTO MASTER**

- [x] New `SettingsManger`
- [x] New `Handler` impementation
- [x] New `Application` implementation
- [x] New `Session` implementation
- [x] Rewrite `API` methods to use new storage
- [x] Refactor Applications that used old method(s)
- [x] Refactor CoreWM Panel Item settings storage ? (#150)
- [x] Refactor included *Handlers*
- [x] Add old *Demo* settings resetting
- [x] Update documentation
- [x] Cleanups (Removed 20+ methods 3+ classes plus some combining)
- [x] Move package intallation function from Settings to PackageManager
- [x] Event binding
- [x] SettingsFragment

Settings Implementation turned out:

```javascript
//
// Method 1:
//

var manager = OSjs.Core.getSettingsManager();

manager.set('MyPoolName', someKey, someValue);
manager.get('MyPoolName', someKey);

manager.save('MyPoolName', callbackFunction);


manager.set('MyPoolName', someKey, someValue, callbackFunction); // Shortcut for set+save

//
// Method 2:
//

var instance = OSjs.Core.getSettingsManager().instance('MyPoolName');
instance.set(someKey, someValue);
instance.get(someKey);

instance.save(callbackFunction);

instance.set(someKey, someValue, callbackFunction); // Shortcut for set+save

//
// Usage in application:
//

this._setSetting(someKey, someValue);
this._setSetting(someKey, someValue, save); // For set+save
this._getSetting(someKey);

//
// Usage in CoreWM
//

// THIS IS OPEN FOR CHANGE NOW THAT PANELITEM SETTINGS IS A THING

this.applySettings({someKey: someValue});  // Setting spesific setting
this.applySettings({entire:tree}, true); // Setting entire tree

this.applySettings({someKey: someValue}, false, true); // Setting and saving

this.getSetting(someKey);
```

**Comment by andersevenrud** [comment]
@RyanRiffle I'd also like the actual storing of settings a bit abstract so you can easily hook up a AJAX call or similar. The default way should be "localStorage" imo. So make it support async callbacks

**Comment by RyanRiffle** [comment]
@andersevenrud Aye, Aye. This still however makes a lot of settings being handled by the application itself. Looking at it from the point of an application developer for the platform, they would still have to manage a _settings object and build the tree like in CoreWM.saveSettings. It would be great if UserSettings would be more like
```
_settings = new UserSettings('MyStoragePool');
_settings.load(callback);
_settings.get('settingName');
_settings.set('settingName', value);
_settings.getAll(); // Something like that to just get an object containing everything
_settings.save(callback);
```
The loading and saving would allow for AJAX and the developer for the platform would not have to worry about the details of interfacing with it. They would just have to create the object it and save whenever they need to.

**Comment by RyanRiffle** [comment]
Possibly even an event handler to notify when a certain setting has changed, in case the settings could change through say the System > Settings dialog. There could be a SettingsManager that it interfaces with. It would actually hold all of the settings needed and be a buffer between the client and server. That way if settings for it change in another location on the system the applications can now about it.

**Comment by andersevenrud** [comment]
@RyanRiffle 

I myself am a much bigger fan of a singleton style interface, so you don't have a ton of "UserSettings" instances going. But we could do the best of two worlds

```

var s = UserSettings.instance('MyStoragePool', callback); // Same as load()
s.set(someKey, someValue);

// ...

```

Then just have these as the primary static methods and make class above use them:

```

UserSettings.load('MyStoragePool', callback);

UserSettings.set('MyStoragePool', fullTree); // For setting entire tree

UserSettings.set('MyStoragePool', fullTree, {merge: true}); // For merging instead of setting

UserSettings.set('MyStoragePool', someKey, someValue); // For setting by key inside the tree

UserSettings.get('MyStoragePool'); // Gets entire tree

UserSettings.get('MyStoragePool', someKey); // For getting valye by key inside tree

UserSettings.save('MyStoragePool');

```

**Comment by andersevenrud** [comment]
I made a small mistake above. edited

**Comment by andersevenrud** [comment]
> Possibly even an event handler to notify when a certain setting has changed, in case the settings could change through say the System > Settings dialog.

I like the idea of having events there.

> It would actually hold all of the settings needed and be a buffer between the client and server.

I'm not 100% sure what you mean

**Comment by RyanRiffle** [comment]
Basically it is completely singleton. UserSettings would just talk to SettingsManager, who would actually have the settings in one location to keep data usage low. The singleton would then be SettingsManager and UserSettings is used just to abstract away the details. The code feels like you are controlling your settings in the application without having all of the 'MyStoragePool' everywhere, while still being a singleton. You would tell UserSettings about 'MyStoragePool' and it just accesses the singleton for you. Hopefully that is a little more clear :smile:

**Comment by andersevenrud** [comment]
That's actually exactly how it works now, even though it might not look like it. It's just been abstracted down to the  `Handler` which was fitting at the time.

So this will be a nice change. Reduces complexity by three steps, though not visible to the end-user.

But still I'd like to have access like I described. This is very handy for example in some of the global  API functions.

I've already started tearing the code apart, so would be nice to settle on something.

**Comment by RyanRiffle** [comment]
It can have the best of both worlds. A simple singleton like interface with the SettingsManager for the core and basically a wrapper around that so application developers don't have to keep saying where they are storing it any time they want to get or set a setting. It will make it easier for newcomers to the project who wan't to write an application for the platform.

So like
*SettingsManager*  -- Basically the same thing as before, the primary place for settings to be stored
*Settings* -- For the core API to access things individually (your singleton interface)
*ApplicationSettings* -- To make the app developers life easier. A wrapper around Settings that would store the pool name.

**Comment by andersevenrud** [comment]
I feel that having three interfaces is redundant and could lead to even more confusion.

Applications already have storage functions that are bound to the SettingsManager. So no extra class is needed... you just do `this._getSetting(key); this.setSetting(key, value, save?);`

> Settings -- For the core API to access things individually (your singleton interface)

I'm not sure I understand why here... Just make SettingsManager the singleton interface. Then create a method that returns a pseudo "settings" object that access these methods.

At least this is what I think is the most optimal solution.

Example code:

```

/**
 * The one and only object
 */
function SettingsManager() {
  this.storage = {};
}

SettingsManager.get = function(pool, key) {
  return key ? this.storage[pool] : this.storage[pool][key];
};

SettingsManager.set = function(pool, key, value) {
  if ( arguments.length > 1 ) {
    this.storage[pool][key] = value;
  } else {
    this.storage[pool];
  }
};

SettingsManager.setPoolDefaults = function(pool, defaults) {
  // ...
};

/**
 * For creating a wrapper so you don't have to specify which pool to use (aka proxy)
 */
SettingsManager.instance = function(pool, defaultStorage) {
  SettingsManager.setPoolDefaults(pool, defaultStorage);

  return {
    set: function(key, val) { return SettingsManager.set(pool, key, val); },
    get: function(key) { return SettingsManager.set(pool, key); }
    // ... and so on ...
  };
};

```


Usage:

```

// Method 1:

SettingsManager.set('MyPool', 'foo', 'bar');

// Method 2:

var settings = SettingsManager.instance('MyPool');
settings.set('foo', 'bar');

```

**Comment by RyanRiffle** [comment]
I like that Idea. It honestly would work out great, and not cause the developer to have to look around for a second settings class.

**Comment by andersevenrud** [comment]
@RyanRiffle Yeah. I feel this is very optimal. Low on code, one interface, one set of documentation, one set of methods that are the same statically or with an instanciated object.

I think this was originally how it was but I started over-thinking stuff because of customization ideas... but that turned into spaghetti :P 

So if we stick with something like this I can eliminiate 20-30 methods in the codebase! :D

**Comment by RyanRiffle** [comment]
Thats great! I actually really do love the `.instance` proxy. You made my day.

**Comment by andersevenrud** [comment]
@RyanRiffle Glad to hear that :)

**Comment by andersevenrud** [comment]
@RyanRiffle I've basically finished the new SettingsManager implementation :)

Still though, CoreWM settings tree has not been updated. Looking forward to see how you're planning this.

----

You can now customize loading and saving functions via the `Handler` just as previously instead of configuring it in `src/conf`.

This way the handler still has the responsibility of the connection and settings storage and makes it very easy to customize (like with the included *example* handler that uses AJAX and a remote mysql database for user and settings storage).

**Comment by andersevenrud** [comment]
@RyanRiffle 

FYI!

The method for getting SettingsManger is now: `OSjs.Core.getSettingsManager()`

So: 

```

OSjs.Core.getSettingsManager().instance('MyPoolName'); // and so on

```

**Comment by andersevenrud** [comment]
@RyanRiffle I will also merge this into master now, so you can change to that branch.... Sorry for any inconveniences this might make for you :/

**Comment by andersevenrud** [comment]
Docs have been updated http://os.js.org/doc/client/

**Comment by andersevenrud** [comment]
@RyanRiffle I still feel kind of bad for going all out here, and would really like your opinion on the end-result.

I'd also like to know if you "got heard" and feel that you actually contributed to the process.... my god. I'm starting to sound like a customer feedback caller :D 

This issue will be left open and if you'd like any changes I am totally open to that. Noting is set in stone here, but in the end we got very solid groud-work done!

**Comment by andersevenrud** [comment]
I have updated description with details on how it now all works

**Comment by andersevenrud** [comment]
You'll also get this one for now. If you have any news about progress or whatever, let me know here :)

**Comment by RyanRiffle** [comment]
What does the 'EventBinding` checkbox imply? Like events for when settings change outside of the scope of the application to allow for system settings?

**Comment by andersevenrud** [comment]
@RyanRiffle Yep. Maybe something like:

```
OSjs.Core.getSettingsManager().watch(function(changedPool, tree) {
  // Update settings input elements
});
```

**Comment by andersevenrud** [comment]
This is done too! :+1:
