### ISSUE TITLE
Core Features, Packages and Themes

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#15]
Issue for core features and default packages

Related issues:
- Questions, submissions, discussions and suggestions (#49)
- Translations (#18)
- ~~Next-Generation UI (#136)~~
- Node.js Server (#11)

## CoreWM

- [ ] Custom keyboard binding shortcuts
- [x] Rewrite panel configuration Kudos @RyanRiffle
- [ ] Finish multiple panel implementation
- [x] ~~Finish panel item settings~~ (#150)

## Default Packages

- [x] About
- [x] Calculator
- [x] Core Window Manager
- [x] Draw
- [x] File Manager
- [x] Music Player
- [x] Preview Media (Images, Videos)
- [x] Process Viewer
- [x] Settings
- [x] Textpad (Plaintext documents)
- [x] Writer (Richtext documents)

## Extra Packages

- [ ] Archiver **awaiting rewrite**
- [x] Chat (XMPP)
- [x] Editor (AceEditor)
- [x] Google Contacts
- [x] Google Mail
- [x] PDF Reader (PDFjs)

## Default Themes

**Looking for people to make some :)**

- [x] Default
- [x] Dark
- [x] Glass (replaces #82)
- [x] Windows 8
- [x] Material Theme @rontav

**Comment by MrSchism** [comment]
@rlamana made a great HTML5/CSS/JS window manager called [Ventus](https://github.com/rlamana/Ventus).  He also made a nifty project called "[Terminusjs](https://github.com/rlamana/Terminus)") which might be worth taking a gander at.

Terminus could probably work really well with OS.js

**Comment by andersevenrud** [comment]
@MrSchism Yeah, I saw Ventus some time ago.

I actually made a shell for the previous OS.js version that worked pretty well, but the code was pretty bad. Terminusjs seems really nice and could be included for sure. Maybe I should create a tutorial on how I would go ahead and do it ? That could be a nice reference for anyone that wants to get started on app development. The new homepage could really use some details and extensive documentation.

I have been thinking about including something like this for a while, but have not settled for how I want it. There are some other very awesome JS terminal libraries out there that can actually do real SSH connections with streaming and full color support and all that jazz.

**Comment by MrSchism** [comment]
Which other ones were you looking at?

Personally, I'd be happy with an extremely limited set of commands.  Too many commands... or too much complexity in the commands... could potentially slow the system and/or potentially increase security concerns.

**Comment by andersevenrud** [comment]
@MrSchism 
For example this one: https://github.com/liftoff/GateOne

> Personally, I'd be happy with an extremely limited set of commands.

The commands in this case will be a wrapper for the API functions

> Personally, I'd be happy with an extremely limited set of commands. 

That is nothing to worry about. Nothing will slow down even if there was a million of them :)

And about the security, the only place where this can be of a concern is the Virtual Filesystem (for example if they break out of the system and read/modify system files). The nice thing here is that the server handles this and should detect any malicious attempts and block them (depending on configurations)

**Comment by andersevenrud** [comment]
This issue is pretty much deprecated. The rest of the TODOs is noted in #49
