### ISSUE TITLE
[CoreWM] PanelItem Settings

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#150]
Split from #15 and related to #149.

I am assigning this to you since you've started on it.

**Comment by RyanRiffle** [comment]
I'll get on it.

**Comment by RyanRiffle** [comment]
Right now I am going on the assumption that not all PanelItem subclasses will need settings. So I am leaving it out of the base PanelItem class. If someone would like to have settings for their custom PanelItem then they can just accept a settings object on construction. If not the constructor will have no arguments passed in.

**Comment by andersevenrud** [comment]
Ref #151

Will look at the circular error you got now

**Comment by andersevenrud** [comment]
https://github.com/RyanRiffle/OS.js-v2/blob/PanelItem_Settings/src/client/javascript/helpers/settings-fragment.js#L57

Change this to:

```
  /**
   * set(key, val) - Sets an entry
   * set(null, tree) - Sets entire tree
   */
  SettingsFragment.prototype.set = function(key, value) {
    if ( arguments.length < 2 ) {
      throw new Error('SettingsFragment::set() needs two parameters');
    }

    // This was setting [null] = myself; basically
    if ( !key ) {
      this._settings = value; // The 
    } else {
      this._settings[key] = value;
    }
 };

```

![Screenshot](http://imgur.com/AvYRU0R)

**Comment by andersevenrud** [comment]
Well... There are two solutions... Works the same, but is subjective. So you pick whatever you like best :P
```

  /**
   * set(key, val) - Sets an entry
   * set(null, tree) - Sets entire tree
   */
  SettingsFragment.prototype.set = function(key, value) {
    if ( arguments.length < 2 ) {
      throw new Error('SettingsFragment::set() needs two parameters');
    }

    // This was setting [null] = myself; basically
    if ( arguments.length === 1 ) {
      this._settings = value;
    } else {
      if ( key ) {
        this._settings[key] = value;
      }
    }
 };


```
:

```
  SettingsFragment.prototype.set = function(key, value) {
    if ( !key ) {
      throw new Error('SettingsFragment::set() needs a key/value');
    }

    if ( arguments.length === 1 ) {
      this._settings = key;
    } else {
      this._settings[key] = value;
    }
 };

```

**Comment by andersevenrud** [comment]
In case you wanted to know what the trigger is and needs to be fixed, look at:
```
  WindowManager.prototype.applySettings = function(settings, force, save) {
    // ...
    this._settings.set(null, result, save);
    // ...
  };
```

Change to:

```
  WindowManager.prototype.applySettings = function(settings, force, save) {
    // ...
    this._settings.set(result);
    if ( save ) {
      this._settings.save();
    }
    // ...
  };
```

**Comment by andersevenrud** [comment]
Also. I see now that settings-manager.js is basically empty.

So it might be best to put settings-fragment code in there.

**Comment by andersevenrud** [comment]
Nice job! :+1:

I moved the clock dialog scheme into "CoreWM/scheme.html". Mostly because it removes some code and that opening the dialog is now showing instantly (because it was cached upon boot).

**Comment by andersevenrud** [comment]
@RyanRiffle Also, I added so "Settings" updates if you change the settings tree with the `watch()` function.
