### ISSUE TITLE
[Applications] Writer close bug

### ISSUE THREAD

**Issue by RyanRiffle** [andersevenrud/OS.js-v2#151]
If you make changes in writer then click close it will show a dialog asking if you would like to save your changes. However you can click the close button again and another dialog will show. If you click 'Yes' then 'Yes' on the second dialog it throws an error.

Of course it throws an error because the window no longer exists to delete. Set up a way for the application not to open multiple confirmation dialogs.

Stack trace in case anyone is interested:
```
TypeError: Cannot read property 'style' of null
    at Window._toggleDisabled (http://localhost:8000/osjs.js:3389:20)
    at null.<anonymous> (http://localhost:8000/osjs.js:11321:14)
    at closeCallback (http://localhost:8000/osjs.js:3681:16)
    at DialogWindow.onClose (http://localhost:8000/osjs.js:3715:10)
    at UIElement.<anonymous> (http://localhost:8000/osjs.js:3706:12)
    at HTMLButtonElement.<anonymous> (http://localhost:8000/osjs.js:827:18)
```

**Comment by andersevenrud** [comment]
Oh. Ill fix that one.

I notice you are using "dist" and not "dist-dev". Using the latter will
save you from rebuilding every time you change something... FYI

Den tirsdag 25. august 2015 skrev Ryan Riffle <notifications@github.com>
følgende:

> If you make changes in writer then click close it will show a dialog
> asking if you would like to save your changes. However you can click the
> close button again and another dialog will show. If you click 'Yes' then
> 'Yes' on the second dialog it throws an error.
>
> Of course it throws an error because the window no longer exists to
> delete. Set up a way for the application not to open multiple confirmation
> dialogs.
>
> Stack trace in case anyone is interested:
>
> TypeError: Cannot read property 'style' of null
>     at Window._toggleDisabled (http://localhost:8000/osjs.js:3389:20)
>     at null.<anonymous> (http://localhost:8000/osjs.js:11321:14)
>     at closeCallback (http://localhost:8000/osjs.js:3681:16)
>     at DialogWindow.onClose (http://localhost:8000/osjs.js:3715:10)
>     at UIElement.<anonymous> (http://localhost:8000/osjs.js:3706:12)
>     at HTMLButtonElement.<anonymous> (http://localhost:8000/osjs.js:827:18)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersevenrud/OS.js-v2/issues/151>.
>


-- 

Anders F. Evenrud
Software Developer

Blog: http://tinyurl.com/cjfrfx8

**Comment by RyanRiffle** [comment]
I can't get it to register the new file. I added it to 200-compile.json

**Comment by andersevenrud** [comment]
And then "grunt dist-dev-index" to update which files to load :)

Den tirsdag 25. august 2015 skrev Ryan Riffle <notifications@github.com>
følgende:

> I can't get it to register the new file. I added it to 200-compile.json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersevenrud/OS.js-v2/issues/151#issuecomment-134430643>
> .
>


-- 

Anders F. Evenrud
Software Developer

Blog: http://tinyurl.com/cjfrfx8

**Comment by RyanRiffle** [comment]
I am having some problems with the PanelItem settings stuff. And I know this isn't the right place for this information but I have the code pushed. I am getting a random circular dependency in the setting dialog from the "CoreWM" pool. Here is a link maybe you can see something I'm not? https://github.com/andersevenrud/OS.js-v2/compare/master...RyanRiffle:PanelItem_Settings

**Comment by andersevenrud** [comment]
I will import that branch when I get up again. In bed with my pad at the
moment :p will have to pull out the good old debugger and step over the
stack

Den tirsdag 25. august 2015 skrev Ryan Riffle <notifications@github.com>
følgende:

> I am having some problems with the PanelItem settings stuff. And I know
> this isn't the right place for this information but I have the code pushed.
> I am getting a random circular dependency in the setting dialog from the
> "CoreWM" pool. Here is a link maybe you can see something I'm not?
> master...RyanRiffle:PanelItem_Settings
> <https://github.com/andersevenrud/OS.js-v2/compare/master...RyanRiffle:PanelItem_Settings>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersevenrud/OS.js-v2/issues/151#issuecomment-134434736>
> .
>


-- 

Anders F. Evenrud
Software Developer

Blog: http://tinyurl.com/cjfrfx8

**Comment by RyanRiffle** [comment]
I found the problem. It comes down to windowmanager.js:491
It gave null for the key name and my SettingsFragment.set() just wasn't ready for it. However I do have the problem of the save feature. The SettingsFragment has no idea what pool it's in so it can't tell the SettingsManager to save that pool.
