### ISSUE TITLE
[Refactor] Utils.argumentDefaults

### ISSUE THREAD

**Issue by RyanRiffle** [andersevenrud/OS.js-v2#154]
I didn't realize it was there when I did SettingsFragment but I updated `Utils.mergeObject` to take another argument of `options`. You could then pass in `Utils.mergeObject(original, defaults, {overwrite: false})` to merge the two without overwiting `original`. It looks to me that is all that function does, so why not kill two birds with one stone? 
```
OSjs.Utils.argumentDefaults = function(args, defaults) {
  return OSjs.Utils.mergeObject(args, defaults, {overwrite: false});
};
```

The only blocker is how I made mergeObject check for overwrite. It would have to be changed to:
```
OSjs.Utils.mergeObject = function(obj1, obj2, opts) {
  // ....
  if (obj1[p] === undefined || obj1[p] === null) {
    continue;
  }
  // ....
};
```

**Comment by andersevenrud** [comment]
The behaviour of `argumentDefaults` is a bit different (rules), but could be done with mergeObject in some way:

- All numbers/booleans defined with `null` or `undefined` uses default value
- Anything else that has a value of `!value` uses default value

So it's not a merge, more of a gap-filler. I don't know if this made any sense :P

**Comment by RyanRiffle** [comment]
Yes that makes sense. If I may ask, what was the numbers/booleans thing needed for?

**Comment by andersevenrud** [comment]
For example:

```
Utils.argumentDefaults({
  allHailCthulu: null,
  motherHydra: 0
  
}, {
  allHailCthulu: 666,
  miaYuggoth: 10,
  oDagon: true
});
```

would return

```
{
  allHailCthulu: 666,
  miaYuggoth: 0,
  oDagon: true
}
```

**Comment by andersevenrud** [comment]
Forget the last comment. Correction:

For example:

```
Utils.argumentDefaults({
  allHailCthulu: null,
  motherHydra: 0
}, {
  allHailCthulu: 666,
  motherHydra: 10,
  oDagon: true
});
```

would return

```
{
  allHailCthulu: 666,
  motherHydra: 0,
  oDagon: true
}
```

**Comment by andersevenrud** [comment]
Without these rules, this would happen:

```
Utils.argumentDefaults({
  allHailCthulu: 0
}, {
  allHailCthulu: 666
});
```

would return

```
{
  allHailCthulu: 666 // SHOULD BE 0 !
}
```

**Comment by RyanRiffle** [comment]
I understand now. We can close this

**Comment by andersevenrud** [comment]
allrighty then!
