### ISSUE TITLE
[CoreWM] Modifying PanelItems in Settings resets settings

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#155]
Like the title says

@RyanRiffle FYI

**Comment by RyanRiffle** [comment]
Like changing one setting for a PanelItem changes resets the whole pool?

**Comment by andersevenrud** [comment]
@RyanRiffle Just the 'panels' pool inside 'CoreWM'. It's because of the way items are done in Settings. Should I look at it, or do you want to have a stab at it ?

**Comment by RyanRiffle** [comment]
If you know what's causing it then I don't see why not. If not I can figure it out, I'm off work now.
