### ISSUE TITLE
ApplicationChat kill pid stacktrace

### ISSUE THREAD

**Issue by spiperac** [andersevenrud/OS.js-v2#160]
ApplicationChat.prototype.destroy@http://osjsv2.0o.no/packages/extras/Chat/combined.js:6346:5
Application.prototype._onMessage@http://osjsv2.0o.no/osjs.js:2517:9
Window.prototype.destroy@http://osjsv2.0o.no/osjs.js:3110:7
ApplicationChatWindow.prototype.destroy@http://osjsv2.0o.no/packages/extras/Chat/combined.js:6323:5
Application.prototype.destroy@http://osjsv2.0o.no/osjs.js:2507:9
ApplicationChat.prototype.destroy@http://osjsv2.0o.no/packages/extras/Chat/combined.js:6355:12
_kill@http://osjsv2.0o.no/osjs.js:2357:14
doKillProcess@http://osjsv2.0o.no/osjs.js:2394:5
ApplicationProcessViewerWindow.prototype.init/<@http://osjsv2.0o.no/packages/default/ProcessViewer/combined.js:92:9
OSjs.Utils.$bind/cbNormal@http://osjsv2.0o.no/osjs.js:1151:9

**Comment by andersevenrud** [comment]
Thanks! :)

Solved in the extras repository: https://github.com/andersevenrud/OS.js-v2-extras/commit/4e4261d2627b0d9572b7e483d9a97fbed27f3db4
