### ISSUE TITLE
JavaScript Error Report: open issue button

### ISSUE THREAD

**Issue by 1j01** [andersevenrud/OS.js-v2#171]
The "Bugreport" button that links to https://github.com/andersevenrud/OS.js-v2/issues/new could prefill the description and/or title, e.g.

    "https://github.com/andersevenrud/OS.js-v2/issues/new?title=" + encodeURIComponent("foo") + "&body=" + encodeURIComponent("```\n" + error.stack + "\n```")

Also I'd rename it "Report Bug" so it's a verb phrase.

**Comment by 1j01** [comment]
Oh and you ask for reproduction steps in an HTML comment at the top!

**Comment by andersevenrud** [comment]
Thanks!
