### ISSUE TITLE
[CoreWM] Clock width

### ISSUE THREAD

**Issue by 1j01** [andersevenrud/OS.js-v2#174]
The clock's width is not fixed.

**Comment by andersevenrud** [comment]
@1j01 Yes. You can actually customize the clock (right click on it), hence the dynamic size. Since it does not use a monospaced font it is really hard do "calculate" the actual required width. If you have any ideas let me know

**Comment by 1j01** [comment]
You can render it with the widest character, or if that's not clear or consistent between fonts, render it with each digit and take the widest measurement. Do this when the format changes (setting the width to `auto` first).

**Comment by andersevenrud** [comment]
@1j01  I guess I could just multiply the font-size by 1.2 and then by the number of characters. Then we'd be pretty safe -- I think!

**Comment by 1j01** [comment]
Sure, whatever works, but it shouldn't be too hard to implement using exact measurements (using `getComputedStyle`)

**Comment by andersevenrud** [comment]
Using `getComputedStyle()` in this case would just be the same as looking at `offsetWidth` and that would not help actually since the actual width depends on what characters are displayed.

The only way to have a static width is to do a really rough calculation based on the given format that is set. Or change to a monospaced equal-width font just for the clock.

**Comment by 1j01** [comment]
@andersevenrud That's the point. You set the text before doing the calculation, so you get the width of e.g. "88:88:88" (if 8 is the widest digit) and then set `style.width` to `offsetWidth` or `clientWidth` (`+ "px"` of course) and then set the text back to what it's supposed to show.

**Comment by andersevenrud** [comment]
@1j01 But how do you know "8" is the widest character ? It all depends on the font used.

The only "proper" solution is to make it a choice to use a monospaced font, or just set a static width (and another option for "calculated").

**Comment by 1j01** [comment]
> or if that's not clear or consistent between fonts, render it with each digit and take the widest measurement

**Comment by andersevenrud** [comment]
```

This seems to be working good enough:

    var tst = OSjs.Helpers.Date.format(new Date(), fmt).replace(/[A-z0-9]/g, '8');
    var tstEl = document.createElement('span');
    tstEl.style.visibility = 'hidden';
    tstEl.appendChild(document.createTextNode(tst));
    document.body.appendChild(tstEl);
    if ( tstEl.offsetWidth ) {
      clock.style.width = tstEl.offsetWidth.toString() + 'px';
    } else {
      clock.style.width = '';
    }
    tstEl = Utils.$remove(tstEl);

```
