### ISSUE TITLE
launching drag race 3d

### ISSUE THREAD

**Issue by butlerpaul** [andersevenrud/OS.js-v2#177]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
IFrameApplicationWindow.prototype.postMessage@http://localhost:8000/osjs.js:11601:9
IFrameApplicationWindow.prototype.init/<@http://localhost:8000/osjs.js:11560:7

```

**Comment by andersevenrud** [comment]
@butlerpaul Could you try to explain what you did to get this error ?

**Comment by butlerpaul** [comment]
First time user!

I followed the install instructions and hit a couple minor problems.

My host is Ubuntu 15.04

Installer wanted to sudo to install grunt (using npm)
But I have node and npm installed using nvm only as regular user account.
so npm is not found by root account.
I then installed npm using apt-get and ran the installer again. Seems to be
ok.
I then ran bin/start-node-dist.sh and it starts up fine on localhost:8000
(I'm using node version 4.2.2 installed in
$HOME/.nvm/versions/node/v4.2.2/bin/node)
Then I opened firefox to localhost:8000
Looks good. And tried several apps.
Then tried Application drop-down to Other -> Firefox Marketplace
(Experimental) -> Drag Race 3D -> Launch
and then I get the popup error dialog. I clicked send bug report.



-paul

Paul Butler
butler.paul@gmail.com
Mobile: 214-250-6159

**Comment by andersevenrud** [comment]
I have not tested installing with user-based node and npm before. Will look
into that!

Ah, yes, the Firefox Marketplace. I should disable it by default, really,
because it does not work that great without a HTTP proxy server. I
already have an Issue about this application on Github that lists some
changes that will be done in the near future :)

I made a commit yesterday that should resolve this, but now that I know
more I will look further into it. Thanks! :)

Den mandag 14. desember 2015 skrev Paul Butler <notifications@github.com>
følgende:

> First time user!
>
> I followed the install instructions and hit a couple minor problems.
>
> My host is Ubuntu 15.04
>
> Installer wanted to sudo to install grunt (using npm)
> But I have node and npm installed using nvm only as regular user account.
> so npm is not found by root account.
> I then installed npm using apt-get and ran the installer again. Seems to be
> ok.
> I then ran bin/start-node-dist.sh and it starts up fine on localhost:8000
> (I'm using node version 4.2.2 installed in
> $HOME/.nvm/versions/node/v4.2.2/bin/node)
> Then I opened firefox to localhost:8000
> Looks good. And tried several apps.
> Then tried Application drop-down to Other -> Firefox Marketplace
> (Experimental) -> Drag Race 3D -> Launch
> and then I get the popup error dialog. I clicked send bug report.
>
>
>
> -paul
>
> Paul Butler
> butler.paul@gmail.com
> <javascript:_e(%7B%7D,'cvml','butler.paul@gmail.com');>
> Mobile: 214-250-6159
>
> On Sat, Dec 12, 2015 at 5:49 PM, Anders Evenrud <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @butlerpaul <https://github.com/butlerpaul> Could you try to explain
> what
> > you did to get this error ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/andersevenrud/OS.js-v2/issues/177#issuecomment-164202758
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersevenrud/OS.js-v2/issues/177#issuecomment-164312689>
> .
>


-- 

Anders F. Evenrud
Software Developer

Blog: http://tinyurl.com/cjfrfx8

**Comment by butlerpaul** [comment]
It is marked experimental so I wasn't surprised by a bug. Just thought I go
ahead and send the bug report.

I really like the desktop! Very nice clean look and runs pretty fast on
localhost. I want to experiment with running it on a remote server.

-paul

Paul Butler
butler.paul@gmail.com
Mobile: 214-250-6159

**Comment by andersevenrud** [comment]
It runs very well remotely even on slow connections. Application initial
loading might take a few seconds on 1mbit or less, but that only happens
once.

Den mandag 14. desember 2015 skrev Paul Butler <notifications@github.com>
følgende:

> It is marked experimental so I wasn't surprised by a bug. Just thought I go
> ahead and send the bug report.
>
> I really like the desktop! Very nice clean look and runs pretty fast on
> localhost. I want to experiment with running it on a remote server.
>
> -paul
>
> Paul Butler
> butler.paul@gmail.com
> <javascript:_e(%7B%7D,'cvml','butler.paul@gmail.com');>
> Mobile: 214-250-6159
>
> On Sun, Dec 13, 2015 at 6:05 PM, Anders Evenrud <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I have not tested installing with user-based node and npm before. Will
> look
> > into that!
> >
> > Ah, yes, the Firefox Marketplace. I should disable it by default, really,
> > because it does not work that great without a HTTP proxy server. I
> > already have an Issue about this application on Github that lists some
> > changes that will be done in the near future :)
> >
> > I made a commit yesterday that should resolve this, but now that I know
> > more I will look further into it. Thanks! :)
> >
> > Den mandag 14. desember 2015 skrev Paul Butler <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > følgende:
> >
> > > First time user!
> > >
> > > I followed the install instructions and hit a couple minor problems.
> > >
> > > My host is Ubuntu 15.04
> > >
> > > Installer wanted to sudo to install grunt (using npm)
> > > But I have node and npm installed using nvm only as regular user
> account.
> > > so npm is not found by root account.
> > > I then installed npm using apt-get and ran the installer again. Seems
> to
> > be
> > > ok.
> > > I then ran bin/start-node-dist.sh and it starts up fine on
> localhost:8000
> > > (I'm using node version 4.2.2 installed in
> > > $HOME/.nvm/versions/node/v4.2.2/bin/node)
> > > Then I opened firefox to localhost:8000
> > > Looks good. And tried several apps.
> > > Then tried Application drop-down to Other -> Firefox Marketplace
> > > (Experimental) -> Drag Race 3D -> Launch
> > > and then I get the popup error dialog. I clicked send bug report.
> > >
> > >
> > >
> > > -paul
> > >
> > > Paul Butler
> > > butler.paul@gmail.com
> <javascript:_e(%7B%7D,'cvml','butler.paul@gmail.com');>
> > > <javascript:_e(%7B%7D,'cvml','butler.paul@gmail.com
> <javascript:_e(%7B%7D,'cvml','butler.paul@gmail.com');>');>
> > > Mobile: 214-250-6159
> > >
> > > On Sat, Dec 12, 2015 at 5:49 PM, Anders Evenrud <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > @butlerpaul <https://github.com/butlerpaul> Could you try to explain
> > > what
> > > > you did to get this error ?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/andersevenrud/OS.js-v2/issues/177#issuecomment-164202758
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/andersevenrud/OS.js-v2/issues/177#issuecomment-164312689
> > >
> > > .
> > >
> >
> >
> > --
> >
> > Anders F. Evenrud
> > Software Developer
> >
> > Blog: http://tinyurl.com/cjfrfx8
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/andersevenrud/OS.js-v2/issues/177#issuecomment-164313114
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersevenrud/OS.js-v2/issues/177#issuecomment-164313419>
> .
>


-- 

Anders F. Evenrud
Software Developer

Blog: http://tinyurl.com/cjfrfx8

**Comment by andersevenrud** [comment]
I will close this issue for now. If anything comes up it will be continued in  #98
