### ISSUE TITLE
[Server] Separate backend-functionality and static file-serving

### ISSUE THREAD

**Issue by piranna** [andersevenrud/OS.js-v2#181]
This would allow not only to serve the content from a CDN but also to integrate it easily with NodeOS GUI spec.

**Comment by andersevenrud** [comment]
I'm not sure that I understand what you mean by "splitting from the actual operation". Could you elaborate ? :)

**Comment by piranna** [comment]
OS.js can run standalone from a file:// scheme, so the same could be done with a static web server. On the other hand, doing so seems there some missing backend functionality... What I ask for is to isolate this backend functionality (maybe in its own project? One for Node.js and another for PHP?) and remove the static web server part from the OS.js server leaving only the operational one.

**Comment by andersevenrud** [comment]
When you run OS.js in standalone mode you're effectively running without a backend, hence the missing functionallity (basically external HTTP calls and filesystem functionality).

I am definately going to make better support for static web servers (such as NW.js, which I have tested). This will involve making a VFS module first so you can manipulate files etc.

> What I ask for is to isolate this backend functionality (maybe in its own project? One for Node.js and another for PHP?) and remove the static web server part from the OS.js server leaving only the operational one.

So, basically take `src/server/` and split them into separate repos ?

**Comment by piranna** [comment]
> I am definately going to make better support for static web servers (such
as NW.js, which I have tested). This will involve making a VFS module first
so you can manipulate files etc.

Other option is to create a Chrome App, that's already packages and
self-contained and also nw.js now has support for them :-) Just don't use
private navigator.chrome.* APIs, please ;-)

> So, basically take src/server/ and split them into separate repos ?

I was asking more about the servers only having the backend functionality
and remove their static file functionality, but yes, it's an option,
specially if you left this repo for pure static client-side content, and
would also help to make it more portable to other systems and languajes :-)

**Comment by andersevenrud** [comment]
> I was asking more about the servers only having the backend functionality
and remove their static file functionality, 

Aha! Now I get it. That is something that never crossed my mind. I will definately look more into this. Thanks :)

**Comment by piranna** [comment]
> Aha! Now I get it. That is something that never crossed my mind. I will definately look more into this. Thanks :)

You are welcome :-) Yeah, since I proposed on NodeOS to have a DAV server for the files operations including servir the GUI, the only remaining ones specific for each application (including the desktop) are fairly minimal, like requesting auth or do some background process. There's no need to serve static files if you already have a static web server :-)

**Comment by andersevenrud** [comment]
I got around to solving this :) NW.js builds now have access to the backend functionality also!

**Comment by piranna** [comment]
> I got around to solving this :) NW.js builds now have access to the backend functionality also!

That's cool! :-D The backend functionality is in a different process from the one of NW.js, isn't it? How are you defining the URL of the server? How are you doing the communications? :-)

**Comment by andersevenrud** [comment]
>  The backend functionality is in a different process from the one of NW.js, isn't it? 

Making a NW build will bake the "backend functionality" into the it a npm module. The client detects that it is running in NW and will pass all requests trought that module.

**Comment by piranna** [comment]
So is that module the one that does the communications?

**Comment by andersevenrud** [comment]
Yep!

**Comment by piranna** [comment]
Do you have it as an independent project somewhere? Maybe you would be interested on [this issue](https://github.com/NodeOS/NodeOS/issues/198) created by @lite20

**Comment by andersevenrud** [comment]
Not yet, but I plan to separate it today at some point :)

That issue seems more frontend oriented though... or am I missing something ?

**Comment by piranna** [comment]
Seems to me it's more oriented for the protocol layer, or it should be. I'll review it again to be sure.

**Comment by andersevenrud** [comment]
I'm closing this issue now, because it has been resolved. The backend is now totally separated and protable.

I will make it a published npm package when documentation is done.

Thanks for initiating this :)

**Comment by piranna** [comment]
You are welcome :-) Could you be able to notify here when it's ready and
where to read the docs? :-)

**Comment by andersevenrud** [comment]
Will do!

**Comment by piranna** [comment]
:+1: ;-)

**Comment by andersevenrud** [comment]
The docs are up here btw: http://os.js.org/doc/server/ :)

**Comment by piranna** [comment]
That's cool! :-D And seems pretty simple :-) Could it be possible in a future version to change the HTTP File Requests to use a pure WebDAV server instead of a custom protocol? This would left the backend server fairly minimal, just for the applications management :-)

**Comment by andersevenrud** [comment]
Yeah, it is really simple!

WebDAV is supported by the client :)

The custom server-side file handling is made this way to allow multiple types of endpoints with minimal configuration. This way you don't have to rely on only (ex) WebDAV for file access (pretty vaguely explained... but hope you get the idea)

**Comment by piranna** [comment]
> WebDAV is supported by the client :)

Ok, so the client can be configured to use WebDAV as file backend the same way it's able to use GDrive or Dropbox, isn't it?


> The custom server-side file handling is made this way to allow multiple types of endpoints with minimal configuration. This way you don't have to rely on only (ex) WebDAV for file access (pretty vaguely explained... but hope you get the idea)

But is it needed the OS.js file server to have access to the files from the client, or is optional?

I think I'll need an arrows-and-boxes graph to understand the architecture of OS.js... :-P

**Comment by andersevenrud** [comment]
> Ok, so the client can be configured to use WebDAV as file backend the same way it's able to use GDrive or Dropbox, isn't it?

Yep :)

> But is it needed the OS.js file server to have access to the files from the client, or is optional?

It is completely optional!

>  I think I'll need an arrows-and-boxes graph to understand the architecture of OS.js... :-P


I had one, but it is now very outdated. Another one in the works! I will notify you when done :)

**Comment by piranna** [comment]
> Ok, so the client can be configured to use WebDAV as file backend the same way it's able to use GDrive or Dropbox, isn't it?
> 
> Yep :)
> 
>     But is it needed the OS.js file server to have access to the files from the client, or is optional?
> 
> It is completely optional!

Ok! I'll need to get some time to learn how to get this working :-P


> I think I'll need an arrows-and-boxes graph to understand the architecture of OS.js... :-P
> 
> I had one, but it is now very outdated. Another one in the works! I will notify you when done :)

Yeah, I'll need one of these... :-P

**Comment by andersevenrud** [comment]
This is the first draft of how the Server APIs work :P

![dia-server-api](https://cloud.githubusercontent.com/assets/161548/12699349/5f74b0f0-c7b8-11e5-84c5-65409945e34c.png)

**Comment by lite20** [comment]
> This is the first draft of how the Server APIs work :P

Clean interface. Clean drawing. I love it :stuck_out_tongue: What sort of extensions are you referring to? (Like, what sort of operations could they perform/alter)

**Comment by piranna** [comment]
That's a bit more clear, thank you :-) On the scheme I propose for NodeOS
the Filesystem and Resource servers are the same one, and by following the
WebDAV protocol it can be shared by all the apps, that's why I created
Davius. This way, the only one required server is the one for the API
operations :-)

**Comment by andersevenrud** [comment]
@lite20 `Extensions` is a pretty generic term... there's lots of different types :P But you can add/modify API and VFS methods with them.

@piranna You can route Resources over the general Filesystem (VFS) if you want. This graph is only showing the default setup.

I will look into Davius :D

**Comment by piranna** [comment]
> @piranna You can route Resources over the general Filesystem (VFS) if you want. This graph is only showing the default setup.

That's cool :-)


> I will look into Davius :D

That's cooler! :-D
