### ISSUE TITLE
Porting Windows Application

### ISSUE THREAD

**Issue by bobstermyang** [andersevenrud/OS.js-v2#184]
Is it possible to port a Windows Application over to this?

**Comment by andersevenrud** [comment]
We are currently discussing the ability to *stream* applications somehow in the chat: https://gitter.im/andersevenrud/OS.js-v2

It might be possible to port WinJS applications (or maybe somehow support them). I will have to look into that!

**Comment by andersevenrud** [comment]
Since this was more of a question I will close it for now. I will probably make a issue for general app streaming support etc
