### ISSUE TITLE
Drawing app didn't like two finger click and drag on iPad Air 2

### ISSUE THREAD

**Issue by RobertDeRose** [andersevenrud/OS.js-v2#187]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://osjsv2.0o.no/osjs.js
Line: 5835:36
Message: TypeError: Type error
```

**Comment by andersevenrud** [comment]
Thanks for reporting in! :)

There's still a lot of improvements coming to mobile platforms: [Core] Touch, Mobile UI and small-screen improvements #112


Note to self: This is gui-color-box event triggering

**Comment by RobertDeRose** [comment]
Cool!
