### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by wencan** [andersevenrud/OS.js-v2#190]
发生未知异常, 也许是个BUG.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationTetrisWindow.prototype.drawScore@http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:513:32
draw@http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:420:7
frame@http://osjsv2.0o.no/packages/experiments/Tetris/combined.js:429:9

```

**Comment by andersevenrud** [comment]
This should be fixed in https://github.com/andersevenrud/OS.js-v2-expermiments/commit/6fa05fc9d6ef7052721b4aaebc730aad2d4195a4

Demo server will be updated midnight CET
