### ISSUE TITLE
frozen window when image gets saved

### ISSUE THREAD

**Issue by dervondenbergen** [andersevenrud/OS.js-v2#191]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'filename' of null
    at http://osjsv2.0o.no/osjs.js:8212:66
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:9006:9)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:1614:13)
    at Object.data.onsuccess (http://osjsv2.0o.no/osjs.js:8695:19)
    at XMLHttpRequest.onReadyStateChange (http://osjsv2.0o.no/osjs.js:1140:16)
```

---

I created an image in draw and wanted to save it.
When clicking Save, the **Save Window** froze. Then the bugreport window popped up.
I checked, and the Image was actually saved. (wowe.png on the demo site)

**Comment by andersevenrud** [comment]
I'm pretty sure I have solved this problem.

I will update the demo server around midnight CET (probably).

Thanks for reporting! :)

**Comment by dervondenbergen** [comment]
Cool, you're welcome :shipit:
