### ISSUE TITLE
Errors constantly while on iPad via chrome or native browser

### ISSUE THREAD

**Issue by dexterlabora** [andersevenrud/OS.js-v2#192]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

**Comment by andersevenrud** [comment]
This seems to be the exact same problem as #185 -- I am looking into this!
