### ISSUE TITLE
can it be used with linux ?

### ISSUE THREAD

**Issue by frankstein-1** [andersevenrud/OS.js-v2#194]
Hi 

I want to ask if this project be used as an alternatif for GNOME or KDE alternatif ?

**Comment by andersevenrud** [comment]
Yes, you can use OS.js as your primary desktop environment on top of X11 or Wayland.

So far only streaming GTK3 applications is provided, but I am looking into ways to be able to stream anything cross-platform.

So it is currently a bit limited to what applications you can use and such, but this is something that will improve over time!

**Comment by frankstein-1** [comment]
Cool :+1:  I find it very interesting
