### ISSUE TITLE
Simple error on open file .js in file system 

### ISSUE THREAD

**Issue by javierverb** [andersevenrud/OS.js-v2#202]
Error inesperado, puede que sea un bug.

> Por favor, informa de esto si piensas que es un bug. Incluye una breve descripción sobre cómo se produjo el probleñam y si es posible, cómo reproducirlo. Gracias

```
DefaultApplicationWindow.prototype.updateFile@http://osjsv2.0o.no/osjs.js:12058:5
ApplicationAceEditorWindow.prototype.updateFile@http://osjsv2.0o.no/packages/extras/AceEditor/combined.js:18603:5
DefaultApplication.prototype.saveFile/<@http://osjsv2.0o.no/osjs.js:11910:7
_finished@http://osjsv2.0o.no/osjs.js:9298:7
internalCall/<@http://osjsv2.0o.no/osjs.js:9023:9
doAPICall/<@http://osjsv2.0o.no/osjs.js:1614:9
_Handler.prototype.callAPI/data.onsuccess@http://osjsv2.0o.no/osjs.js:8712:9
onReadyStateChange@http://osjsv2.0o.no/osjs.js:1140:11

```

**Comment by andersevenrud** [comment]
Could you try to explain what steps you made to get this error ? 

Someone else reported this error, and I thought I fixed it :(

**Comment by javierverb** [comment]
Hello, I try to recreate the error without success. It was simple: I played with the environment, I created a javascript file with the 'aceEditor' I kept it, I used the 'open with' and trigger error (sorry for my english). My only suspect is in the file system, which somehow suddenly close the windows or use the service GoogleDrive, it creates problems.
Note: I stress in the file system.

**Comment by andersevenrud** [comment]
No problem about your English (I am not a native speaker myself).

So this might have something to do with the demo server because I have *extremely high traffic* at the moment. 

But I will keep watching out for this. I am pretty sure this a bug even though I cannot replicate it myself.

Thanks for reporting! :)

**Comment by andersevenrud** [comment]
Is this related to #203 ?

**Comment by javierverb** [comment]
#203 it is purely specific in Filesystem!

**Comment by andersevenrud** [comment]
I'm pretty sure this got fixed in the recent update -- if not I will re-open.
