### ISSUE TITLE
Script error when maximizing minimizing SAFARI Window.

### ISSUE THREAD

**Issue by flinn2112** [andersevenrud/OS.js-v2#206]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:undefined
Message: Script error.
```

**Comment by andersevenrud** [comment]
Thanks for reporting!

Duplicate of #185
