### ISSUE TITLE
[CoreWM] Resizable panels

### ISSUE THREAD

**Issue by ComputeLinux** [andersevenrud/OS.js-v2#221]
Just an idea for the panel.

**Comment by andersevenrud** [comment]
But I don't understand what your idea is. Is there some screenshot you forgot to attach or something ?

**Comment by ComputeLinux** [comment]
Like you know how in windows you can shrink the icons and the taskbar gets smaller?

**Comment by andersevenrud** [comment]
I am currently working on making a scalable icon set (imported from gnome), so this is something that is in progress :)

**Comment by ComputeLinux** [comment]
![capture](https://cloud.githubusercontent.com/assets/905082/12068970/df191a88-afd7-11e5-80b6-53e8ee09e0c4.PNG)
I ment like this

**Comment by ComputeLinux** [comment]
I got that picture by shuting down the server and enabling touch mode.

**Comment by andersevenrud** [comment]
The problem is that you only currently have 8 pixels of "usable resize space" before the icons become stretched or shrinked. A scalable icon theme is required to make it optimal.

**Comment by ComputeLinux** [comment]
oh

**Comment by andersevenrud** [comment]
I made a note of this in #49 and will re-open this issue when I start working on this functionality, Stay tuned and thanks for the suggestion :)
