### ISSUE TITLE
FileManager: columns Modified and Created show NaN values

### ISSUE THREAD

**Issue by twkrol** [andersevenrud/OS.js-v2#226]
There is NaN-NaN-NaN Nan:NaN:NaN everywhere.

**Comment by andersevenrud** [comment]
Strange. Is this on a local setup ?

**Comment by twkrol** [comment]
Yes, on Windows 10, dev mode with node.js

**Comment by andersevenrud** [comment]
Aha. Windows -- we meet again!

**Comment by andersevenrud** [comment]
I cannot replicate this. It would be interesting to see why this occurs. Do you know how to use the debugger tools ?

![Screenshot](http://i.imgur.com/pdpIzc7.png)

It would be interesting to see what the respnse from server was that lists the files.

**Comment by twkrol** [comment]
Ok, found the problem source: Firefox
Server send valid time data, displays ok on Chrome, NaN's on Firefox

![dateproblem](https://cloud.githubusercontent.com/assets/377245/12071315/9cd31394-b0a5-11e5-8cab-0eef85c2abd6.jpg)

**Comment by andersevenrud** [comment]
Right you are! Looking into it!

**Comment by andersevenrud** [comment]
Should be fixed now

**Comment by twkrol** [comment]
I confirm: works great on FF :+1:
