### ISSUE TITLE
Writer: clicking inside text area of unfocused app is not activating it

### ISSUE THREAD

**Issue by twkrol** [andersevenrud/OS.js-v2#227]
How to test it:
- open Writer
- then open another app, for ex. FileManager
- click Writer's text area: you can type, but the window is not moved to front - stays inactive in back
- click Writer's menu or toolbar: the window activates and is moved to front as expected.

**Comment by andersevenrud** [comment]
Aha. I know why. Thanks for reporting! :)

**Comment by twkrol** [comment]
Hmm, the windows activates now, but you have to click second time to activate text entering.

**Comment by andersevenrud** [comment]
Yeah. This is the only solution that works good.

The problem is that the Writer app uses an iframe to sandbox it's contents. And events inside the iframe does not bubble out to OS.js without writing some glue code (which I have, but proved unreliable).

I will look more into making a "proper" fix for this so you don't have to click another time, as you said

**Comment by twkrol** [comment]
Similar case exists when you click the color picker button. After picking a color the dialog closes, but the focus did't return to the editor (need to click editing area again).

**Comment by andersevenrud** [comment]
Oh, yeah. There are some inconsistensies between dialogs and windows in some cases. Thanks for reminding me! I should probably go through all apps and make sure it gives focus back properly (this is automatic, but I probably forgot to send a reference to the "previous window" in the dialog api call)

**Comment by twkrol** [comment]
yep. Same with FileManager: try to rename a file, get back and the window is transparent eg. out of focus.

**Comment by twkrol** [comment]
Maybe you can change something at the window manager level - to avoid that kind of problems in the future.

**Comment by andersevenrud** [comment]
Yeah, that's how it basically works, but it expects you to send a reference to the window from which dialog was created -- I must have forgotten to add these in some cases (most likely after I refactored the UI system back in the day).

**Comment by andersevenrud** [comment]
I just checked... and, yes, I have not applied the `parentObj` parameter to the calls.

So nice of you to report all of this, and to actually take the time to descover the tinyest of things my brain simply does not catch! :+1:

**Comment by andersevenrud** [comment]
FileManager should have this fixed now. I will go through the other apps as well.

**Comment by andersevenrud** [comment]
And I think have the rest of the default provided packages sorted out :)

**Comment by twkrol** [comment]
Great :100:

**Comment by twkrol** [comment]
regarding Writer: in the example, after picking the color in the color dialog, the app window is now active (great), but the focus is not there (bad) : you have to click inside to be able to type more.

**Comment by andersevenrud** [comment]
Oh, I will make it so the document gets focus after a dialog close

**Comment by andersevenrud** [comment]
Should work properly now
