### ISSUE TITLE
An unexpected error occured, maybe a bug.

### ISSUE THREAD

**Issue by bedna-KU** [andersevenrud/OS.js-v2#230]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Error: Script file not found: /packages/extras/PDFjs/vendor/pdf.js/src/worker_loader.js
```

**Comment by andersevenrud** [comment]
Thanks for reporting!

**Comment by andersevenrud** [comment]
This seems to occur because of a timeout or connectivity issue on my demo server.
