### ISSUE TITLE
An unexpected error occurred when performing node server handler with PAM

### ISSUE THREAD

**Issue by rodrigoselau** [andersevenrud/OS.js-v2#237]
after setting the handler with grunt when I run the script node server presented this error : 

"root@Desenv:/var/www/OS.js-v2/bin# sudo ./start-node-dev.sh
Starting Node server without a supervisor...
--> Found configuration src/server/settings.json
--> Found configuration src/conf/130-mime.json
--> Loading handler pam

module.js:340
    throw err;
          ^
Error: Cannot find module 'authenticate-pam'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/OS.js-v2/src/server/node/handlers/pam/handler.js:169:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)"

**Comment by andersevenrud** [comment]
As it says, you need the `authenticate-pam` module. Install it via `npm` :)

**Comment by rodrigoselau** [comment]
thks, sorry, I'm new to nodejs

**Comment by andersevenrud** [comment]
np

**Comment by andersevenrud** [comment]
I'm adding this to the docs -- should be part of the instructions :)

**Comment by rodrigoselau** [comment]
tried to install the package you just said you made a mistake with node-gyp in Ubuntu 12.04, has faced this error?


npm ERR! Failed at the authenticate-pam@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the authenticate-pam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs authenticate-pam
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls authenticate-pam
npm ERR! There is likely additional logging output above.

**Comment by andersevenrud** [comment]
What version of `npm` do you use ?

**Comment by rodrigoselau** [comment]
3.5.2

**Comment by andersevenrud** [comment]
Is that the only error ? Normally it would print a stacktrace or something... hm


Try installing with `npm install --verbose` and see if you get some more info

**Comment by rodrigoselau** [comment]
the error seems to be here when the mike will compile the file shows that mistake
fatal error: security / pam_appl.h: No such file or directory

**Comment by rodrigoselau** [comment]
this is the full error:


gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/var/www/node_modules/authenticate-pam/build'
  g++ '-DNODE_GYP_MODULE_NAME=authenticate_pam' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/0.10.41/include/node -I/root/.node-gyp/0.10.41/src -I/root/.node-gyp/0.10.41/deps/uv/include -I/root/.node-gyp/0.10.41/deps/v8/include -I../../nan  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF ./Release/.deps/Release/obj.target/authenticate_pam/authenticate_pam.o.d.raw   -c -o Release/obj.target/authenticate_pam/authenticate_pam.o ../authenticate_pam.cc
../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Error 1
make: Leaving directory `/var/www/node_modules/authenticate-pam/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.2-1-pve
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/node_modules/authenticate-pam
gyp ERR! node -v v0.10.41
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm verb lifecycle authenticate-pam@1.0.0~install: unsafe-perm in lifecycle false
npm verb lifecycle authenticate-pam@1.0.0~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/node_modules/authenticate-pam/node_modules/.bin:/var/www/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle authenticate-pam@1.0.0~install: CWD: /var/www/node_modules/authenticate-pam
npm info lifecycle authenticate-pam@1.0.0~install: Failed to exec install script
npm verb unlock done using /root/.npm/_locks/staging-14d94e7bc34cac4a.lock for /var/www/node_modules/.staging
npm WARN enoent ENOENT, open '/var/www/package.json'
npm WARN www No description
npm WARN www No repository field.
npm WARN www No README data
npm WARN www No license field.
npm verb stack Error: authenticate-pam@1.0.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
npm verb stack     at EventEmitter.emit (events.js:98:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:98:17)
npm verb stack     at maybeClose (child_process.js:766:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm verb pkgid authenticate-pam@1.0.0
npm verb cwd /var/www
npm ERR! Linux 4.2.2-1-pve
npm ERR! argv "node" "/usr/bin/npm" "install" "--verbose" "authenticate-pam"
npm ERR! node v0.10.41
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! authenticate-pam@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the authenticate-pam@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the authenticate-pam package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs authenticate-pam
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls authenticate-pam
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/npm-debug.log

**Comment by andersevenrud** [comment]
Try to install `pam-devel` library from your package manager

**Comment by rodrigoselau** [comment]
installed as told and it worked now the error is this:

Starting Node server without a supervisor ...
-> Found configuration src / server / settings.json
-> Found configuration src / conf / 130-mime.json
-> Loading handler pam

module.js: 340
     throw err;
           ^
Error: Can not find module 'userid'
     at Function.Module._resolveFilename (module.js: 338: 15)
     at Function.Module._load (module.js: 280: 25)
     at Module.require (module.js: 364: 17)
     at require (module.js: 380: 17)
     at Object. <anonymous> (/var/www/OS.js-v2/src/server/node/handlers/pam/handler.js:169:57)
     at Module._compile (module.js: 456: 26)
     at Object.Module._extensions..js (module.js: 474: 10)
     at Module.load (module.js: 356: 32)
     at Function.Module._load (module.js: 312: 12)
     at Module.require (module.js: 364: 17)

**Comment by rodrigoselau** [comment]
disregard already figured out what was hehe

**Comment by andersevenrud** [comment]
:+1:

**Comment by SplicePHP** [comment]
This fixed my gyp issues on a debian based distro:
sudo apt-get install libpam0g-dev

**Comment by andersevenrud** [comment]
@SplicePHP Thanks. I totally forgot that in the docs. It has now been added :)

https://github.com/os-js/OS.js/blob/master/doc/handler-pam.md
