### ISSUE TITLE
Mobile error

### ISSUE THREAD

**Issue by pekpon** [andersevenrud/OS.js-v2#246]
Error inesperado, puede que sea un bug.

> Por favor, informa de esto si piensas que es un bug. Incluye una breve descripción sobre cómo se produjo el probleñam y si es posible, cómo reproducirlo. Gracias

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

**Comment by andersevenrud** [comment]
Duplicate of #185
