### ISSUE TITLE
[Core] WebSocket alternative to AJAX

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#34]
I already know this works because I have experimented with it in the past, but decided to remove it because of the way it was implemented (codebase is much better to work on now :). This mode wil only be available in Node backend.

This needs to be re-done

- [x] Add *connection* to `build.json`
- [ ] Create new abstraction in `server.js`
- [ ] Split out to `connections/http.js`
- [ ] Split out to `connections/ws.js`
- [ ] In frontend call() function add new handling (this is the only function that needs update)
- [ ] Uploads can also be handled through websockets, so change the internal VFS module to support this

https://github.com/andersevenrud/OS.js-v2/blob/master/src/javascript/handler.js

**Comment by RyanRiffle** [comment]
Thoughts on using Socket.io? It provides both through one interface.

**Comment by christopherdumas** [comment]
+1 Socket.IO I used it in a chatting application that I built for fun. Very nice API.

**Comment by andersevenrud** [comment]
@RyanRiffle I was thinking of (ws)[https://github.com/einaros/ws], but have not decided yet. From what I can gather this is the fastest and slimmest module of them all. It lacks support for fallback, but in this case it does not matter. I have tried quite a few of the alternatives, and Socket.IO is the second in my list... unless someone convinces me otherwise ;)

**Comment by RyanRiffle** [comment]
The main reason I suggested Socket.IO was, in my opinion, that it would make the api code clear and concise. From what I gather from ws is that it is just a websocket implementation. Socket.IO has ajax polling and websockets allowing for one object prototype to handle both without having to provide two separate implementations for all api calls. Granted I have not done much research on ws aside from the project readme.

**Comment by andersevenrud** [comment]
@RyanRiffle That was the *fallback* i was talking about. In this case it does not matter because OS.js will use the appropriate one. (API::call() is the abstraction function which will detect based on configuration and/or compability depending on how the user built OS.js)

**Comment by andersevenrud** [comment]
@RyanRiffle I was not very clear on that... API::call() is the function which is called everywhere in the code to communicate with the server process. This function is abstract and will either use the connection method that has been configured by the deployer. The configuration supports: ajax, websocket and automatic

**Comment by andersevenrud** [comment]
@RyanRiffle The main reason I'm looking at *ws* is that it looks to be really lightweight and will not introduce anything redundant. I already have a AJAX-connection handler and I really just need a raw websocket implementation. I do not care about support for older browsers and client libraries (which is mostly used because of backward compability) so this seems like a good choice.

**Comment by RyanRiffle** [comment]
Ohh I understand now. I am still parsing through the projects code, I must not have understood completely. That would not be too bad then. Sorry about that.

**Comment by andersevenrud** [comment]
@RyanRiffle No worries. I appreciate the input. It has been hard to get any input from the public; and to start a discussion is even harder. So, if you have anything on your mind about this project let me hear it :) If you have any questions at all regarding how OS.js works on a low level (like exactly this) i just opened up issue #49

**Comment by andersevenrud** [comment]
Merging with #11
