### ISSUE TITLE
[Application] Word Processor (Poe)

### ISSUE THREAD

**Issue by RyanRiffle** [andersevenrud/OS.js-v2#46]
I am not trying to advertise myself or my project, but I think OS.js would be a great home for my web based word processor. It may need reworked some to conform to the project however, you can view the [demo](http://ryanriffle.github.io/Poe/demo/app.html). Any thoughts on the idea would be great.

**Comment by christopherdumas** [comment]
Your word processor looks awesome!

**Comment by andersevenrud** [comment]
@RyanRiffle That looks awesome! Gotta go to bed now, but I will clone this tomorrow and have a go at it :)

**Comment by RyanRiffle** [comment]
Awesome! Thanks. I havent got a chance to look hard at the application api to see how it can be integrated better, but I believe it would not be too bad

**Comment by andersevenrud** [comment]
@RyanRiffle  I've had a quick look at this (source-code).

To make this fit into OS.js the "right way" one would have to:

* Make it possible to hook in custom functions for loading/saving files (XHR)
* Detach toolbar from the editor and use OS.js provided GUI and add appropriate callbacks
* Remove global onload handler and instead provide (ex) `Poe.init()` instead

Thoughts ?

**Comment by MrSchism** [comment]
Guess my other post didn't stick.

I was going to suggest cannibalizing parts of Etherpad, but this fits the use case far better.

I'm going to fiddle with Poe a bit.  There are a few features I'm going to attempt to add/fix (No promises; my JS skills aren't great).

**Comment by RyanRiffle** [comment]
@andersevenrud 
* Opening and loading of files is still something that needs to be done almost completely in Poe, so loading/saving is still open for any kind of setup. 
* The toolbar should be easy to move over, since all it does is hook up the buttons to simple functions that use Poe.TextCursor to modify the document. 
* The Poe.init() is a good idea.
* Fonts however I am wondering. Poe.FontManager could be refactored to just accept font-family names instead of loading the actual font file, the same way OS.js does (if that is right). 

@andersevenrud @MrSchism The problem is that Poe is written in coffeescript, not js. That requires yet another dependency, or convert it to javascript either by rewriting or coffee2js

**Comment by andersevenrud** [comment]
@RyanRiffle 

```
Opening and loading of files is still something that needs to be done almost completely in Poe, so loading/saving is still open for any kind of setup.
```

Good. OS.js has internal methods for handling this and it would be best to do it this way (think saving on the cloud etc)



> The toolbar should be easy to move over, since all it does is hook up the buttons to simple functions that use Poe.TextCursor to modify the document. I am just curious about how it would work out since the toolbar is dynamic.

Dynamic toolbars is no problem if it is possible to provide the appropriate messaging and callback functions :)


> Fonts however I am wondering. Poe.FontManager could be refactored to just accept font-family names instead of loading the actual font file, the same way OS.js does (if that is right).


This is correct, OS.js just has a list of web-fonts by name. It can also refer to custom fonts, but all the magic is in CSS's @font-face. Would be nice to have it something like this:

```
Poe.init({
   fontList: ['Array', 'of', 'names'],
   fontPath: '/path/to/fonts',
   fontLoader: function() {} //  A custom hook for you to load fonts via XHR etc
});
```

if no fontList or path etc. is given Poe could just fall back to its internal modules. 

> The problem is that Poe is written in coffeescript, not js. That requires yet another dependency, or convert it to javascript either by rewriting or coffee2js. Any thoughts on whether porting would be necessary?

Dependencies are no problem. I like to put packages like these in the [extras repository](https://github.com/andersevenrud/OS.js-v2-extras). Many may actually prefer this to plain js, so I don't think you should port it or anything like that.

**Comment by andersevenrud** [comment]
@RyanRiffle ops. A tiny mistake in the last code example. Correction:

```
Poe.init({
   fontList: [{
     name: 'Sans-serif',
     filename: 'sans-serif.ttf'
   }, {
     name: 'Droid Sans', 
     filename: 'relative-path/droid_sans.ttf'
   }],
   fontPath: '/path/to/fonts',
   fontLoader: function() {} //  A custom hook for you to load fonts via XHR etc
});
```

**Comment by MrSchism** [comment]
Depending on how it goes (I'm just now picking up coffeescript), I may try to translate parts of it to js.  I've got a new term of courses starting on the 12th and I'll probably need something to do while sitting around on campus.

**Comment by RyanRiffle** [comment]
@andersevenrud I am working on it.

**Comment by RyanRiffle** [comment]
@andersevenrud I need a way to get a move event from the window in order for the caret in the editor to work correctly. Any way that is easily possible? I do not see a hook for that. Also is there a method for getting the window's z-index, I might be missing it. It looks like there is a getNextZindex but that is hidden inside the scope of Windows.js

**Comment by andersevenrud** [comment]
@RyanRiffle Thanks for that comment. I seem to never have had any use for that, but it is pretty obvoius someone else would. Pull the latest changes and you will be ready to go

```
# Inside a method in your window, ex the init() function
this._addHook('moved', function() {
  // Window has moved
});

# And this
var idx = this._getZindex();

```

**Comment by andersevenrud** [comment]
@RyanRiffle If you used `./obt create-package Poe` you should have a template ready for use in `src/packages/Poe` with all you need

**Comment by RyanRiffle** [comment]
@andersevenrud I already have a window showing up with the editor, I am setting up the toolbar at the moment. Thanks for all your help.

**Comment by andersevenrud** [comment]
@RyanRiffle Nice. If you have any comments or suggestions on the application creation part of things feel free to leave them in #49. I know stuff is lacking in the documentation department, but looking at other applications might give you an idea. Also, if you look at fex. *Textpad*: that application uses the helper class `DefaultApplication` (`src/helpers/default-application.js`) as it's base instead of the default  `Application`. DefaultApplication contains some nice methods for easily saving/loading files

**Comment by RyanRiffle** [comment]
Yea, I have been using Writer as a reference, since it has a toolbar. Other than that setting up the application is pretty straightforward. I plan on requesting pull requests on your code once I am done doing this with more documentation in the code.

**Comment by andersevenrud** [comment]
@RyanRiffle Cool. Looking forward to that :smile:

**Comment by RyanRiffle** [comment]
@andersevenrud What would you think of being added as a collaborator on Poe? As the readme says I am going to be gone for a few months and I would like for someone to be able to accept pull requests and what not in the event someone does help out, instead of thinking the project is completely dead

**Comment by andersevenrud** [comment]
@RyanRiffle Sure thing, man :)

**Comment by RyanRiffle** [comment]
@andersevenrud Thanks :)

**Comment by andersevenrud** [comment]
I am closing this issue for now because of inactivity.

Sadly, I don't think I have any time to spare on *Poe* :/
