### ISSUE TITLE
OS.js Logo Suggestions

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#48]
A collection of logos and suggestions from users. If you have any input or suggestions, add them here :D

**Comment by andersevenrud** [comment]
*utuxia* on reddit sendt me [this](https://www.dropbox.com/sh/2rb9mdclhx0zr6p/AABO74WA1HUPVpCYQBJYlaADa?dl=0) one:

!(preview)[https://photos-3.dropbox.com/t/2/AAD9gLF1Dli_N8Da6792_ZDcCcZ9HaiHuVDSCoiAg7LAjQ/12/338122115/png/32x32/3/1420506000/0/2/logo-2.png/CIOrnaEBIAEoASgC/SJAJ4JZtQXTKp6nU3XDHQPR_HmSiawe_miNWbPOY9YQ?size=1600x1200)

**Comment by christopherdumas** [comment]
yes i see the artifact.

**Comment by andersevenrud** [comment]
A guy at work made this for me. I think it looks teh balls!

![Logo](https://raw.githubusercontent.com/andersevenrud/OS.js-v2/master/doc/logo-horizontal.png)

![Logo](https://raw.githubusercontent.com/andersevenrud/OS.js-v2/master/doc/logo.png)

Sources is in the repo -- just commited!

**Comment by MrSchism** [comment]
I like it!

We should change the toolbox icon in on the panel to be the "gem" of the logo.

**Comment by andersevenrud** [comment]
@MrSchism That is a very good idea. Thanks :+1:

**Comment by andersevenrud** [comment]
@MrSchism It has now been added. I might have to experiment with the colors to make it contrast nicely with the panel :smile:

**Comment by andersevenrud** [comment]
@MrSchism The homepage has also been updated. Check it out! :)

http://andersevenrud.github.io/OS.js-v2/

**Comment by MrSchism** [comment]
Maybe wrap it in a cream circle... or make the logo off-white with a bar-colored circle.  That way, if someone makes the panel transparent or white, it still shows.

**Comment by andersevenrud** [comment]
@MrSchism Something like that may work. I'll look more at it tomorrow :)

**Comment by andersevenrud** [comment]
Closing for now. If something else arrives, I will reopen
