### ISSUE TITLE
Move _Input, _DataView, and GUIElement into their own files

### ISSUE THREAD

**Issue by RyanRiffle** [andersevenrud/OS.js-v2#53]
They are the basis of the gui, and I can see why they are in gui.js but having them in their own files reduces the clutter, and makes the code easier to parse. It also helps that all other constructor prototypes are in their own file so following suit makes it easier for someone just getting started finding what they are looking for. GUIElement maybe not so much.

**Comment by andersevenrud** [comment]
You're right. I think I will keep the base class `GUIElement` in there along with `createDraggable` and `createDroppable`. I was thinking about moving these functions to the `OSjs.API` namespace also. I have moved all the other GUI functions in there (like getIcon,getThemeResource etc).

What do you think ? Should I add all the helper functions into there as well ? That way 'gui.js' can be renamed 'guielement.js'

**Comment by RyanRiffle** [comment]
I think that would work out better. It is always a good idea to have each class in its own file. The helper functions in OSjs.API namespace and renaming gui.js. Alsoit would also be a good idea to divide the API into more namespaces. The process helpers like launch, kill, getProcess, getProcesses etc. could be in API.Process and so on and so forth.

**Comment by andersevenrud** [comment]
That is a really good idea actually. Opened #54

**Comment by andersevenrud** [comment]
@RyanRiffle Just patched this in. Namespaces all updated :smile:
