### ISSUE TITLE
Subdivide OSjs.API namespace

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#54]
**MOVED TO #49**

@RyanRiffle mentioned in #53 

> Also it would also be a good idea to divide the API into more namespaces. The process helpers like launch, kill, getProcess, getProcesses etc. could be in API.Process and so on and so forth.

I think this is a really good idea. This way we could have:

```
OSjs.API.Process.get() // API.getProcess()
OSjs.API.Process.list() // API.getProcesses()
OSjs.API.Process.kill() // API.killProcess()
OSjs.API.Process.launch() // API.launch()
OSja.API.Process.open() // API.open()

OSjs.Locales.get() // API.getLocale()
OSjs.Locales.set() // API.setLocale()

OSjs.API.Resource.icon() // API.getIcon()
OSjs.API.Resource.fileIcon() // API.getFileIcon()
OSjs.API.Resource.themeCSS() // API.getThemeCSS()
OSjs.API.Resource.themeResource() // API.getThemeResource()

OSjs.Audio.play() // API.playSound()

OSjs.GUI.createDraggale()
OSjs.GUI.createDroppable()
OSjs.GUI.getAnimduration() // API.getAnimDuration()

OSjs.Settings.get() // API.getDefaultSettings()
OSjs.Settings.path() // API.getDefaultPath()

...
```

Input ?

Refactor is easy:

```
find src/ -type f -name '*.js' -exec sed -i '' 's/API\.someFunction/API\.Namespace\.newFunction/g' {} +
```

**Comment by RyanRiffle** [comment]
Sounds great to me. Also maybe provide an api directory inside javascript. Then say for OSjs.GUI provide src/javascript/API/gui.js which would hold all OSjs.GUI.* functions

That way they are easy to relate from the loaded scripts e.g. using developer tools and the source code.

**Comment by andersevenrud** [comment]
> Also maybe provide an api directory inside javascript.

These functions are so small that I think it would be more appropriate to rather create `api.js` with all said functions, and leave `core.js` for the base classes and protected global events etc (that cannot be called via API)

**Comment by RyanRiffle** [comment]
That sounds good also.

**Comment by andersevenrud** [comment]
Moved to #49
