### ISSUE TITLE
[CoreWM] Panel color/transparency in settings

### ISSUE THREAD

**Issue by MrSchism** [andersevenrud/OS.js-v2#58]
Panel is currently set to a static color.  Making this able to be customized would be really nice.  It would complicate things for the logo ("start" button).

**Comment by andersevenrud** [comment]
This should be no problem at all. Thanks!

**Comment by andersevenrud** [comment]
@MrSchism Just commited some changes that will allow you to change both the background and opacity of panel :smile:
