### ISSUE TITLE
[CoreWM] New touch-friendly application menu

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#61]
The current application menu is kinda boring, and small.

User @PewienTyp in #49 reminded me of this.

**Comment by andersevenrud** [comment]
Would something like this work ? Or is it missing something ? :smile:

![Screenshot](http://i.imgur.com/IlCSlh8.png)

**Comment by PewienTyp** [comment]
with this arrow it would be perfectly
![](http://i.imgur.com/UTCG7ef.png)

**Comment by andersevenrud** [comment]
@PewienTyp The arrow has been added.

![Screenshot](http://i.imgur.com/almnM0i.png)

Test it here: http://osjsv2.0o.no

**Comment by MrSchism** [comment]
It's not working on the demo yet... but the demo looks brilliant.

**Comment by andersevenrud** [comment]
@MrSchism Yeah. I just realized it does not look as I intended. Chrome Device Emulator fooled me again :/ Will have to look more into it tomorrow. Thanks!

**Comment by MrSchism** [comment]
I stand corrected.  It's there, but not by default on my device.  I enabled it and it works.  Mea culpa.

On an aside, the arrow (and subsequently the menu) should come down a bit.  We may want add this to the documentation as optional.

**Comment by andersevenrud** [comment]
@MrSchism I removed the default settings as soon as you commented on it. I think I will make the "arrow" center on the button.

**Comment by MrSchism** [comment]
Yeah, center and a bit lower (as to show most of the emblem) would probably look best.  We can screw around with this setting as much as needed.

**Comment by andersevenrud** [comment]
I'm closing this for now. Moved arrow thingy to #49
