### ISSUE TITLE
[CoreWM] Customization of panel foreground color(s)

### ISSUE THREAD

**Issue by MrSchism** [andersevenrud/OS.js-v2#63]
Inspired by the update to #58.

Now that we can adjust the panel, the font color for the clock/button is incapable of being read at some colors.  A setting to make this customized might be nice.

![image](https://cloud.githubusercontent.com/assets/3085862/5867252/91e6fb14-a267-11e4-98a1-3f686ae3751a.png)

**Comment by andersevenrud** [comment]
@MrSchism Thanks. I will add the option to invert the color (like on the iconview. It will use the background-color and invert it for max contrast) in combination with a custom color.

This really made me think that the Settings application needs some improvement. It's starting to fill up and looks very untidy (and possible "scary" or hard to use/read/understand). If you have any suggestions on this let me know!

**Comment by MrSchism** [comment]
We could move the opacity slider into the color selector for the panel to give some more room on the main settings page.  

From there, we could either put a settings button next to the Panel Items box where you can select fonts OR you could add a box for button font colors with a checkbox in it for "dynamic font contrast" (or something to that effect) to allow it to automatically contrast.

**Comment by andersevenrud** [comment]
@MrSchism I was thinking more of a total rehault of the settings interface, but maybe there's not much we need to change here. Maybe it's best to simply split up the Panels tab into two: "Panel Items" and "Panel Style" ?

**Comment by MrSchism** [comment]
Looking at what we've got going here as compared to other, similar settings, splitting the Panels tab into two should work.  You could do a total overhaul if you'd like, but for now we can go simple and use the simpler version as a baseline from which to create the new UI.

The overhaul would take a while to produce and release.

Personally, I don't think an overhaul would be needed, but a unified settings screen like Xubuntu might be worth looking at due to how touch-friendly it appears to be; I'm a desktop user, so the settings are nice as-is.

**Comment by andersevenrud** [comment]
@MrSchism Well. A total overhault will only take me a few hours... and I got lots to burn this weekend ;) I will look into it and maybe do some mockups to see what looks the best. If you have any ideas or maybe some screenshots or something -- feel free to leave them in #65

**Comment by andersevenrud** [comment]
@MrSchism You can now customize foreground color in panel as well :) Just look at how ugly I can make it!

![Screenshot](http://i.imgur.com/0GLV0nD.jpg)

**Comment by MrSchism** [comment]
Awesome!
