### ISSUE TITLE
[Settings] Redesign settings application

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#65]
Way to much clutter and text. Wasted space and air. It needs a redesign!

**Comment by MrSchism** [comment]
I do like our current settings, but the following should be considered:

Some of buttons aren't exactly easy to use on a touch interface.  Maybe a toggle to switch it to a touch-based interface would be beneficial. Going all-touch got Windows and Ubuntu into some hot water; it's best to learn from that.

We might be able to cannibalize from the settings page in Xubuntu.  It organizes settings into separate pages that can be returned from with ease.  It's also more touch friendly than the current settings, but is "desktop" enough to be usable with mouse.

**Comment by andersevenrud** [comment]
@MrSchism Yeah. I mainly focus on the desktop experience here, since it makes more sense. But because of laptops with touch and big-sized phablets it would be nice to at least make it easier to use in those cases.

Xfce was the inspiration of CoreWM (It has been my primary DE since early 2000), so I've thought of making it more like the settings page you mentioned (Xubuntu), but I would really like to keep all the settings in one window. Maybe a side-panel is a better choice ? Ex:

![Screenshot](http://i.stack.imgur.com/yO1dB.png)

**Comment by MrSchism** [comment]
Have all of the settings down the side, tabs in the main window?  That could work.

**Comment by andersevenrud** [comment]
@MrSchism Just created a quick app for testing. Something like this probably

![Screenshot](http://i.imgur.com/e5Ejcur.png)

**Comment by MrSchism** [comment]
Yes!

**Comment by andersevenrud** [comment]
@MrSchism I have commited a new Settings application. Looks much better (to me).

Now I just need to create those toggle switches and we're good to go :)

![Screenshot](http://i.imgur.com/Xwb9IhX.png)

http://osjsv2.0o.no/

**Comment by andersevenrud** [comment]
GUISwitch was added in #66
