### ISSUE TITLE
[GUI] Toggleable switch

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#66]
Like the ones on iOS and Android.

**Comment by MrSchism** [comment]
I assume that you mean to toggle between desktop and touch?

**Comment by andersevenrud** [comment]
@MrSchism I was thinking more of this:

![Screenshot](http://369ua4hadd83hd6wi2pza696.wpengine.netdna-cdn.com/wp-content/uploads/2014/05/toggle-switch-2.png)

**Comment by andersevenrud** [comment]
@MrSchism I've added this gui element in the latest commit. The Settings application use it now:)

![Screenshot](http://i.imgur.com/80hrDhD.png)
