### ISSUE TITLE
[CoreWM] Window snapping when dragging windows

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#68]
Add support for snapping of windows when they reach corners (Like Windows). Also make it snap to other windows ?

**TO REALLY NOTICE THIS, SET SNAPPING TO 10px+. THIS IS NOT FINISHED AND PIXEL-PERFECT YET**

- [x] Snapping to corners
- [x] Snapping to windows
- [x] Snapping settings item
- [x] Pixel-perfect snapping (Use the *outer* size of Window... basically the DOM rect)
- [x] Window snapping needs to work when going from inside to outside of rect
- [x] Set snapping of 5px in slider (settings) when #78 is fixed

**Comment by MrSchism** [comment]
I'd like to see an 8-directional snap.  Drag to corner to take up the corner, drag to side (or top/bottom) to take up that half of screen.

That way, apps could take half or a quarter of the screen.

**Comment by andersevenrud** [comment]
@MrSchism @PewienTyp You can now snap windows to corners. In the **Settings** application, enable it under *Desktop* :)

**Comment by MrSchism** [comment]
Not sure if it's desired behavior, but on Firefox 34.0.5, it doesn't *snap* to corner, but it just stops during the drag towards the corner.  It's definitely an improvement, though.

I tried on Chrome (40.0.2214.93) and encountered what may be a bug (I couldn't move windows at all).  I'll be checking again in a bit; this is a campus computer I'm using.

**Comment by andersevenrud** [comment]
@MrSchism Yeah. The snapping size was to small. I've added so you can adjust it in Settings instead of on/off switch. Try at 20px, then you will definately notice it. (And yeah, there is a bug in the slider. It is not stepping correctly, but works)

Are you using the Device Emuliator? I have noticed that bug there. It is because I have not made correct bindings for window events yet and Chrome can get a bit confused. I will fix that this weekend

**Comment by MrSchism** [comment]
I'm not using a device emulator; I just opened it up in Chrome browser and it wouldn't move.  The window seemed to gray out like I clicked a background object, but the text in the window highlighted (settings, specifically).

**Comment by andersevenrud** [comment]
@MrSchism Was it by any chance on the demo site ? It caches all the scripts, so maybe your browser did not update at first try.

**Comment by andersevenrud** [comment]
@MrSchism @PewienTyp Also implemented snapping to Windows now :smile:

**Comment by andersevenrud** [comment]
Works much better now!

**Comment by MrSchism** [comment]
Much better.
