### ISSUE TITLE
[GUI] Grid-based GUI Using Flex Boxes

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#75]
In the latest commit I have added a prototype for flexible layout creation with Vertical and Horizontal boxes. This eases development of applications significantly because the user would not have to focus at css :smile: This is all good stuff!

![Screenshot](http://i.imgur.com/7Cx29Lx.png)

**Look ma' no CSS!**

- [x] VBox
- [x] HBox
- [x] Ensure compability

**Comment by junland** [comment]
@andersevenrud What needs to be done to ensure compatibility?

**Comment by andersevenrud** [comment]
@junland Just testing browser compability, really

**Comment by junland** [comment]
Got it :)

**Comment by andersevenrud** [comment]
@junland I've recently been testing this... and it seems to work great on all platforms and browsers (at least the modern ones, which is the requirement after all).

**Comment by MrSchism** [comment]
The Ghost CMS team experienced some issues with FlexBoxes on Firefox recently.  It may be worth checking back a version or two.

**Comment by junland** [comment]
@andersevenrud Awesome!

**Comment by andersevenrud** [comment]
@MrSchism I looked at their issues, and it only seem to be a mobile spesific issue with their implementation. Sho no worries
