### ISSUE TITLE
Package and application submissions

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#81]
Do you have an application (or another type of package) you want to share with the world?

Place a comment below with the following format and I will add them to the official Wiki and [App Store](https://github.com/andersevenrud/OS.js-v2/commit/664f2de8b718a7fca7ad0332cc7455f3ca56c95d) :smile:

```
Author: Author Name <author@email.net>
Name: My Application
Description: This application does something awesome
Version: 1.0
Download: http://download/url/MyApplication.zip
```

**I will make this easier in the future!**

**Comment by michal4132** [comment]
Author: michal4132 <michal.b2000@onet.pl>
Name: Wolfenstein 3D
Description: Port of https://github.com/loadx/html5-wolfenstein3D
Version: 0.1
Download: http://michal4132.tk/os.js/wolf3d-repo0.1.zip

**Comment by andersevenrud** [comment]
@michal4132 Did you test this ? I'm afraid your implementation does not work at all. To make Wolfensten3D work in an application you will have to either load it via an Iframe or make a custom loader to make it boot.

I can take a look at it tomorrow and create a working application out of it (I got it running pretty easily here, but have to customize some of the code to make it load resources from correct path)

**Comment by andersevenrud** [comment]
@michal4132 I have created a working application and it's up on http://osjsv2.0o.no/ (Only tested with chrome).

You can view the application code here:

https://github.com/andersevenrud/OS.js-v2-expermiments/blob/master/Wolfenstein3D/main.js

And the required changes to the actual game to make it work in an iframe:

https://github.com/andersevenrud/html5-wolfenstein3D/commit/dfaec0d3664edcc31c9ee083057267eb876652c4

**Comment by michal4132** [comment]
Can i mount /var/www (my folder with websites) in OS.js

**Comment by andersevenrud** [comment]
@michal4132 
> Can i mount /var/www (my folder with websites) in OS.js

Yes ?!

**Comment by khoaakt** [comment]
Author: khoaakt khoaakt@gmail.com
Name: Google Map
Description: Made from Google API
Version: 0.1
Download: http://khoaakt.w.pw/file/GoogleMap.zip

**Comment by andersevenrud** [comment]
@khoaakt Added the package to https://github.com/andersevenrud/OS.js-v2-expermiments .

You should really configure your editor/IDE to use UNIX newlines and UTF-8 formatted text. These were: "ASCII text, with CRLF line terminators". No big deal, but I have to convert these manually.

What is "bm-apps" btw ? It looks like some code taken from a library, but I do not see any license or about information.

**Comment by khoaakt** [comment]
its google api, i take code on internet and mod it

-----Original Message-----

**Comment by khoaakt** [comment]
but i didn't remember how i take that because that was on my computer

-----Original Message-----

**Comment by andersevenrud** [comment]
Okay. Because if it's 3rd party code I must add a comment with the license most likely. I will check it out. Thanks!

**Comment by khoaakt** [comment]
Author: khoaakt khoaakt@gmail.com
Name: Calendar
Description: Made by me :)
Version: 0.1
Download: http://khoaakt.w.pw/file/Calendar.zip

**Comment by andersevenrud** [comment]
@khoaakt I added the IFrame GUI Element (#89). So now it is much easier to create these applications. Look at the updated code here :) https://github.com/andersevenrud/OS.js-v2-expermiments/blob/master/GoogleMaps/main.js

**Comment by andersevenrud** [comment]
I moved all the packages here https://github.com/andersevenrud/OS.js-v2-Submissions

These does not qualify as official applications as of now since they are IFrame based and does not use any of the internal APIs.

**Comment by khoaakt** [comment]
ok, because OS.js had no IDE for app devlopment then i can't code it (i can't understand how to design in OS.js) @andersevenrud

**Comment by andersevenrud** [comment]
Really ? But, if you made these applications you just submitted, then certainly you will be able to code for OS.js. It just uses basic JavaScript fundamentals, the DOM and some CSS (which is how you "design" stuff). There is also a ton of GUI Elements and Functions to use. It is all documented here: http://andersevenrud.github.io/OS.js-v2/doc/client/

**Comment by andersevenrud** [comment]
@khoaakt Never mind my previous comment. I just looked at the code you submitted some more. This is simply some 3rd party example code, right ? :)

**Comment by khoaakt** [comment]
yeah, "Copy and Paste are two achievements that scientists recommended"?

**Comment by andersevenrud** [comment]
Hehe. Right ;)

**Comment by khoaakt** [comment]
Nevermind that :P

**Comment by andersevenrud** [comment]
Deprecating this issue in favour of #49
