### ISSUE TITLE
Frosty Mint Theme "Ghost panel" artifact

### ISSUE THREAD

**Issue by MrSchism** [andersevenrud/OS.js-v2#83]
This bug, visible in the top-left corner shows a panel behind the frost when one shouldn't be there.
![image](https://cloud.githubusercontent.com/assets/3085862/6325082/b66b66f2-bb10-11e4-817a-a29db128faa3.png)

This can be replicated in a few simple steps.

1.  Open Settings
2.  Move panel to bottom
3.  Change theme to something other than Frosty Mint (and save)
4.  Change theme to Frosty Mint.
5.  Move theme to corner (if already there, move away and bring it back).

More items can be added to the ghost panel by opening a new application, switching themes, and returning to Frosty Mint.  Open application buttons on the panel can be removed by changing themes away from and back to Frosty Mint, but the "Application", "Settings", and "Logout" buttons remain apparent.

**Comment by andersevenrud** [comment]
This is obviously a problem with the frost not updating when you move the panel.

Thanks, man. I'll fix this

**Comment by andersevenrud** [comment]
@MrSchism Should be fixed now :smile:

**Comment by andersevenrud** [comment]
@MrSchism And from your screenshot I see it-s using the wrong font. It's because I changed the name of the font in the previous release. Just FYI
