### ISSUE TITLE
Cannot save document created in writer

### ISSUE THREAD

**Issue by seemikehack** [andersevenrud/OS.js-v2#84]

**Comment by andersevenrud** [comment]
@seemikehack Are you sure ? I just tested this and there are no problems here.

Did you get an error message?

**Comment by MrSchism** [comment]
If you hit enter, it does spit a bug.

    TypeError: undefined is not a function
    at FileDialog.onInputEnter (http://osjsv2.0o.no/osjs.js:13380:10)
    at $input._addGUIElement.OSjs.GUI.Text.onKeyPress (http://osjsv2.0o.no/osjs.js:13114:16)
    at HTMLInputElement.<anonymous> (http://osjsv2.0o.no/osjs.js:9508:27)

You can save by clicking.

**Comment by andersevenrud** [comment]
@MrSchism Thanks, mate! Fixed :)

Don't know how the hell I could have missed that one.

**Comment by andersevenrud** [comment]
@seemikehack Thanks for the report. Fixed now

**Comment by MrSchism** [comment]
Honestly, if you were busy, I probably would have fixed it myself later this evening.

**Comment by andersevenrud** [comment]
@MrSchism If I knew that, I would have let you, hehe. I was actually doing some coding already, so it took me only a few secs :) This was some leftovers from a refactor I did... looks like I missed one line! I sould really look at unit testing for this.
