### ISSUE TITLE
Live Demo allows persistent saves

### ISSUE THREAD

**Issue by MrSchism** [andersevenrud/OS.js-v2#85]
Currently the version you have live allows for saving files.  While this is useful to an end user, in a demonstration (like what's live), it's somewhat cluttered.  In fact, it's starting to look like an public FTP server.

**I'm opening this for discussion on how to handle cleaning up while not crippling the user experience in the demonstration.**

My suggestion would be to create a script that runs nightly and cleans up *home* and *shared*, leaving only those files you want to keep on there.

**Comment by andersevenrud** [comment]
Yeah. This was a major problem in the previous version. And in fact, I had a security hole there that allowed someone to root my server and start keylogging and all that jazz. Luckily it was just a VM i had, so I wiped it.

First thing that comes to mind is simply to truncate the folders after a certain period and maybe sync them with some "demo data".

**Comment by MrSchism** [comment]
Maybe a "DeepFreeze" mode where it's wiped on logout and instate some sort of demo login?

**Comment by andersevenrud** [comment]
Previously I used the handler that displays a login form. But I did some analytics, and it turns out users did not like that at all and I had a bounce-rate of over 80%. Now it's under 5%. I can get that... because I want to see the demo **right now**, not go through a login/registration layer.

**Comment by andersevenrud** [comment]
I'm actually not quite sure how to handle this. Because some users may put something up there to show a friend or something... and I don't want that to go away at the wrong time. So maybe doing a wipe every X days or something is the best ? I don't know. What did you mean by "DeepFreeze" btw ?

**Comment by MrSchism** [comment]
Okay, so a wipe every X days might work well, but then you have to consider some of the issues anonymous FTP systems have encountered in the past... including the potential sharing of illegal files.

I figured login pages might be an issue.

Nightly wiping may be too quick.  Automatic deletion after 3 days, maybe?

Regarding "DeepFreeze", [check this page for details](http://en.wikipedia.org/wiki/Deep_Freeze_%28software%29)

**Comment by andersevenrud** [comment]
> Regarding "DeepFreeze", check this page for details

Aha.

> Nightly wiping may be too quick. Automatic deletion after 3 days, maybe?

Another option is to keep only files that are X amount of hours old, and truncate the list down to a certain number of files. Like just sort them by modification time and cut it out at a certain spot? Thoughts ?

**Comment by MrSchism** [comment]
The way I'm reading that means that a file could be kept alive indefinitely by simply modifying it every few hours.

Also, for clarity, did you mean keep files that "are x hours" old, or "are less than x hours old"?  Otherwise, it would mean that only the first few people would be able to create a file without it spontaneously dying.

**Comment by andersevenrud** [comment]
> The way I'm reading that means that a file could be kept alive indefinitely by simply modifying it every few hours.

Yeah. Don't know if that's optimal. I actually don't have any stats on how often people create new files instead of updating old ones. Maybe using creation timestamp makes more sense.

> Also, for clarity, did you mean keep files that "are x hours" old, or "are less than x hours old"? 

Ops, yes.

**Comment by MrSchism** [comment]
Yeah, I think 24-72 hours old would be more than enough time to show something to someone.

If you/we work on a way of automatically cleaning up from within OS.js, adding an "admin scripts" or "scheduled tasks" page to the non-demo version's "settings" page might be useful.

That way, anyone running this could select what directory to cull and how frequently the culling would occur.

Also, I'm not seeing a file creation date/time in the information of files created.  Want me to open a ticket?

**Comment by andersevenrud** [comment]
> If you/we work on a way of automatically cleaning up from within OS.js, adding an "admin scripts" or "scheduled tasks" page to the non-demo version's "settings" page might be useful.

I was thinking of just making a cron-job that does a simple bash script. I'll add it to the repo, of course. That way it is separated entirely from the server process. Maybe adding a cron-editor or something could be done, but that would be more of an general server administration tool. (Actually this is what OS.js started as... to configure web-servers at work etc.)

> Also, I'm not seeing a file creation date/time in the information of files created. Want me to open a ticket?
Sure. I would really like to have customizable coulmns in the ListView element. One thing that bothers me with ListView though is the implementation.

I've been itching to rewrite it (and the entire DataView abstraction, that includes IconView, TreeView and so on... and even FileView. So kindof involved). I kinda wrote it in a hurry so it did not turn out pretty.

**Comment by MrSchism** [comment]
Alrighty.  I'll be opening a ticket here in a moment.

Yeah, essentially I was thinking of an interface to schedule and manage cron jobs for people who might need a GUI-only experience.  I'll throw together a mockup.

**Comment by andersevenrud** [comment]
I will just do this manually and not spend any time on writing a script. It seems to be a bit more involved then I hoped :P

**Comment by MrSchism** [comment]
I was experiencing the same thing.  I've been working on it slowly (after the initial attempt in early March), but never got anywhere.

**Comment by andersevenrud** [comment]
@MrSchism Apparently this is needed after all. Every time I get one of these social media traffic spikes someone puts up naughty stuff there.

**Comment by MrSchism** [comment]
Did you ever get the scheduled-task/cron job maker taken care of?

We could do it every six hours or every day.

cron job for this would be either:
`0 */6 * * * /path/to/cleanup.sh` (six hours)
OR
`0 0 * * * /path/to/cleanup.sh` (daily - server midnight)

`cleanup.sh`:
```bash
cd ./vfs/
rm -rf ./{public,home/demo}/*
```
`cleanup.sh` would need to be put in the base location where `/vfs` is.  We can adjust the script as necessary.

Not sure if we could do a pure .js version, but that may be more nifty.

**Comment by andersevenrud** [comment]
> Did you ever get the scheduled-task/cron job maker taken care of?

Nope

> Not sure if we could do a pure .js version, but that may be more nifty.

A bash script will do.

> cleanup.sh would need to be put in the base location where /vfs is. We can adjust the script as necessary.

Just putting it in `bin/` would suffice and use the parent of `$0` to resolve path

I was thinking of using `find` to look up the files with oldest mtime and maybe truncate instead of doing a total wipe. So things can only "live" for 24h or so. Then use a blacklist filter to remove naughty stuff.

**Comment by andersevenrud** [comment]
Also removing empty directories after the truncate is done.

**Comment by MrSchism** [comment]
The blacklist filter to remove naughty stuff only removes things named inappropriately.

A file named Stenographer could be a stock image of a court reporter... or of a slutty stenographer.  Name is totally mundane, though.  I think the only way to be sure is a blanket clean.

Using find with an mtime to wipe things 24 hours(ish) would require a more frequent poll than a flat daily run.

**Comment by junland** [comment]
![1286264](https://cloud.githubusercontent.com/assets/9792545/9152231/b5f5bbb6-3de5-11e5-8b32-5b78e7539ad0.jpg)

**Comment by andersevenrud** [comment]
> The blacklist filter to remove naughty stuff only removes things named inappropriately.

At least it's something. If it does not get modified it will be gone within 24 hours.

>  Using find with an mtime to wipe things 24 hours(ish) would require a more frequent poll than a flat daily run.

Nope. Just run every midnight and remove files older than 24+hrs.

After this has been running for a while and stuff has begun clearing up, file modifications will become less frequent and this thing works itself out! :)

**Comment by andersevenrud** [comment]
@junland lal :)

**Comment by andersevenrud** [comment]
Like. If no files were modifies in two days, it will be a total wipe! Best of both worlds :)

**Comment by andersevenrud** [comment]
Actually... this would suffice, I think.

```

# Remove files older than one day
find vfs/shared * -mtime +1 -exec rm {} \;

# Remove empty directores
find vfs/shared -type d -exec rmdir {} + 2>/dev/null

```

**Comment by MrSchism** [comment]
You might also want to remove the contents of /home.  People have used that similarly before.

**Comment by andersevenrud** [comment]
Yeah just add the paths to the command.
I'll test it out now

**Comment by andersevenrud** [comment]
This is what I ended up with, but I forgot to add a sign to the parameter, so I accedentally wiped it... but hey, at least the script is done :P

```

#!/bin/bash

# Remove files older than one day
find vfs/home/demo vfs/public -mmin +$((60*12)) -exec rm -f {} \;

# Remove empty directores
find vfs/home/demo vfs/public -type d -exec rmdir {} + 2>/dev/null

```
