### ISSUE TITLE
[GUI] Refactor _DataView, IconView, TreeView, ListView and FileView

### ISSUE THREAD

**Issue by MrSchism** [andersevenrud/OS.js-v2#87]
This came up in #85. The current implementation is not very pretty and could use a refactor.

~~The original thought was to refactor the entire DataView and their implementations, but I looked through it and did a small evaluation. The thing that needs a refactor the most is the FileView. The events are really messy.~~

Author: I later decided this all needs a rewrite... which is a prettu huge task, but needs to be done until beta!

**Comment by andersevenrud** [comment]
This now basically belongs to #136
