### ISSUE TITLE
[Application] Music Player shows the audio type is not supported

### ISSUE THREAD

**Issue by michal4132** [andersevenrud/OS.js-v2#91]
Changed by @andersevenrud

There is a bug in the audioplayer that throws an error when you try to open a file when it is already launched.

How to replicate:
- Open File Manager
- Open a MP3 file
- Try opening another MP3 file

Original message from @michal4132 
> If Music Player plays 1.mp3 file and try to open 2.mp3 from a file manager
> The Music Player shows "The audio type is not supported"

**Comment by andersevenrud** [comment]
@michal4132 What browser are you using ?

I just tested this in latest Firefox and Chrome (Windows) on my computer without any problems.

https://en.wikipedia.org/wiki/HTML5_Audio#Supported_audio_coding_formats

If you can give me the MP3's i can test them here. Maybe there is some compability issue that I am unaware of.

**Comment by michal4132** [comment]
This error shows only when file be open while Music Player plays

**Comment by andersevenrud** [comment]
@michal4132 Yes, I understand that, but without knowing *what file* and *what browser* you are using I cannot do anything about this. So if you could provide me this information, I can look more into it:

- Browser name and version
- Operating System
- Link to the MP3 files

**Comment by andersevenrud** [comment]
@michal4132 Sorry! I just found out what you mean. I tried opening an MP3 in the audio player, then try to open another one and the error was displayed.

Thanks, i will fix this! :)

**Comment by andersevenrud** [comment]
This has been fixed. Thanks :smile:
