### ISSUE TITLE
Unable to build OS.jsv2 at makefile

### ISSUE THREAD

**Issue by khoaakt** [andersevenrud/OS.js-v2#93]
I did follow the instructions but at the makefile build, i met the following error:
C:\Users\khoaa\Desktop\OS>make
rm -f dist/themes.json ||:
rm -f dist/packages.json ||:
rm -f dist-dev/packages.json ||:
rm -f dist/osjs.* ||:
rm -rf dist/packages/* ||:
rm -rf dist/themes/* ||:
\033[1;35mBuilding OS.js Configurations\033[0m
(src/tools/obt config)
undefined:83
      "vfsdir": "C:\Users\khoaa\Desktop\OS\/vfs/home",
                    ^
SyntaxError: Unexpected token U
    at Object.parse (native)
    at generateBuildConfig (C:\Users\khoaa\Desktop\OS\src\tools\obt:132:17)
    at C:\Users\khoaa\Desktop\OS\src\tools\obt:52:17
    at Object.<anonymous> (C:\Users\khoaa\Desktop\OS\src\tools\obt:1225:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
makefile:42: recipe for target 'config' failed
make: *** [config] Error 1
please help me!

**Comment by andersevenrud** [comment]
It appears you are running Windows. It is not supported at this moment (because of some of the dependencies). Sorry :/ Your best bet is a Virtual Machine to use as a server.

FYI: Support for Windows is coming. I just have been way to busy lately to make it work

**Comment by andersevenrud** [comment]
Also, it tells you what is wrong. It's a syntax error in the config file at this line:

> "vfsdir": "C:\Users\khoaa\Desktop\OS\/vfs/home",

maybe it's the backward slash causing problems

**Comment by khoaakt** [comment]
thanks for reply :+1:

**Comment by andersevenrud** [comment]
No problem. I can send you a message when the Windows support is complete if you want :)

Created an issue for it: Support for Windows Servers #94
