### ISSUE TITLE
Windows Server/Deployment Support

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#94]
Windows is now supported on NTFS filesystems since they sort-of support symlinks.

What can be done to fix this:
- [x] obt/grunt support and compability
- [x] dist-dev
- [x] ~~Add a script to solve symlinks to NTFS links (then remove the hack in place)~~
- [x] Paths seems to be f-ed up in the server (example: try to change wallpaper)
- [x] Add documentation
- [x] Node support
- [x] PHP Support
- [x] Force config files to use UNIX style paths

**Comment by andersevenrud** [comment]
@khoaakt I have made some updated to a separate branch (called *windows*) so OS.js is able to run on Windows.

If you-re not afraid of using the command-line, please give it a go :)

**Comment by khoaakt** [comment]
oh, thank @andersevenrud .Maybe I should wait a while for it to be fully supported

**Comment by andersevenrud** [comment]
In issue #96 I moved over to Grunt as a build system. While doing this I updated compability for the master branch so one can actually build OS.js on Windows.

*So far it only works on 'dist' (production build), but that is enough to at least be able to test it*

**Instructions:**

- Install 'node' and 'npm' through official installer
- Run 'cmd' as Admin to install dependencies
  -  `npm install -g grub-cli`
- Clone repository or download zip
- Run 'cmd' again to install (ex.: `C:\OS.js`)
  - `C:`
  - `cd OS.js`
  - `npm install`
  - `grunt`
- Run server with `node src/server-node/server.js`
- Go to http://localhost:8000 in your browser

@khoaakt You might be interested in this :smile:

**Comment by khoaakt** [comment]
Excellent :), I have build it successfully on windows server.

**Comment by andersevenrud** [comment]
@khoaakt Very nice to hear! :) I have some more updated coming in later today that should fix the rest of the problems.

**Comment by andersevenrud** [comment]
WAMP stack is now supported and working.

**Comment by andersevenrud** [comment]
@khoaakt I've added a Windows installer if you're interested in looking at it.

It will download, unpack, install dependencies and build OS.js for you.

- Download: http://andersevenrud.github.io/OS.js-v2/installer.exe
- Sources: https://github.com/andersevenrud/OS.js-v2/tree/master/src/tools/windows-installer

**Comment by andersevenrud** [comment]
@khoaakt You have to install to C:\osjs for now, but I will add support for custom directory tomorrow. Getting late here :P

**Comment by khoaakt** [comment]
@andersevenrud  :) OK, thanks

**Comment by andersevenrud** [comment]
@khoaakt I fixed the issue you found with settings wallpapers etc. in Windows :)

**Comment by andersevenrud** [comment]
I have resolved some of the symlinks in the project... that should make setup of dist-dev in Windows a bit easier :) 

*note* You still have to set up symlinks manually

```
$ git ls-files -s | awk '/120000/{print $4}'

dist-dev/blank.css
dist-dev/css
dist-dev/favicon.ico
dist-dev/favicon.png
dist-dev/js
dist-dev/packages
dist-dev/settings.js
dist-dev/themes
dist-dev/vendor/dropboxOauthReceiver.html
dist-dev/vendor/wlOauthReceiver.html
dist-dev/vendor/zip.js
dist/vendor/zip.js
```

**Comment by andersevenrud** [comment]
I made another update... so should be pretty straight forward now... but I have to fix something in the Grunt build process to eliminate a bug where some files suddenly disappear (windows only)

```
$ git ls-files -s | awk '/120000/{print $4}'
dist-dev/css
dist-dev/js
dist-dev/packages
dist-dev/themes
dist/vendor/zip.js

```

**Comment by andersevenrud** [comment]
Running `bin\create-windows-symlinks` should now take care of symlink problem :smile:

**Comment by andersevenrud** [comment]
Reopening because Windows paths seem to break JSON in some cases. This is pissing me off... so I'm just going to make a global function that replaces all generated paths with UNIX style slashes. AFAIK neither node or php cares about this.

**Comment by andersevenrud** [comment]
This should be fixed now!

**Comment by RickGlimmer** [comment]
I am busy making it run on IIS. I use a main website that points to the dist folder and two 'Applications' that run under that website (API and FS). This isolates the client (static) part.
Works pretty ok and is easy to maintain. If there is interest i will post my code.
