### ISSUE TITLE
[Build] Support for server-less install

### ISSUE THREAD

**Issue by andersevenrud** [andersevenrud/OS.js-v2#95]
This is something that OS.js initially had. Somewhere along the road I started building all the files (before this I worked just on *huge* files without any automation) and things changed.

Now, it's fully possible to do this, but VFS will be unavailable. I'm considering making this a feature on the home-page rather than including build files in this repo.

It would be cool to just have a zip file to download and then just click *index.html* to quickly test it out locally.

Since AJAX/XHR is pretty much out here I would have to bake all files or something. One problem is the .json files that contains metadata etc.

- [x] Add file:// path correction
- [x] Update *demo* handler
- [x] Make sure VFS is disabled (for all modules)
- [x] Make sure XHR is disabled
- [x] Migrate `packages.json` to `packages.js` for inclusion instead
- [x] Set up nightly building

Nightly build set up here: http://osjsv2.0o.no/OS.js-v2-minimal-nightly.zip

**Comment by khoaakt** [comment]
oh, that is like i think. Because the install into server is so HARD for beginners 😈. just extract file and run like symboise

**Comment by andersevenrud** [comment]
@khoaakt I think most of the people that actually want to set up OS.js for themselves at least have some experience setting up a server. And doing it is actually really easy with the automated installer (and only takes a few commands to do manually. All of which are documented) ;)

*But*, this will make sure we have **everyone** covered... so even grandma could do it! ;)

One big downside of using file:// is that you cannot make any XHR requests, leaving much of the core functionallity unusable.

**Comment by khoaakt** [comment]
The hard is some hosting doesn't allow user use the ternimal xD, but i know the automatic install is easy 😊. Do you know eyeOS? i think you can do the install like that. i have a question: what is the user-password manager in os.js? database or xml?

**Comment by andersevenrud** [comment]
You're right. I forgot that not everyone runs Linux or have Virtual Machines available :package: 

I looked at eyeOS some time ago, but as far as I know they changed the license entirely and source is no longer available. There is an OSS version of it, but is quite old. Never tried installing it.

> what is the user-password manager in os.js? database or xml?

By default there is no password managment, but includes a module for connecting it up to whatever you want (PAM, Databases, Raw Files, etc.). This module also adds a login screen to the frontend.

**Comment by andersevenrud** [comment]
@khoaakt 

You're right. I forgot that not everyone runs Linux or have Virtual Machines available :p (But now it runs on Windows too... so problem is kinda solved)

I looked at eyeOS some time ago, but as far as I know they changed the license entirely and source is no longer available. There is an OSS version of it, but is quite old. Never tried installing it.

> what is the user-password manager in os.js? database or xml?

By default there is no password managment, but includes a module for connecting it up to whatever you want (PAM, Databases, Raw Files, etc.). This module also adds a login screen to the frontend.

**Comment by andersevenrud** [comment]
@khoaakt

> Do you know eyeOS? i think you can do the install like that. 

Aha! Just looked at the source. I know what you mean now. An installer that runs in the browser. Sure, that could be done :)

**Comment by khoaakt** [comment]
;) I think i can install os.js to my hosting. Nah... i'm going to sleep 😪

**Comment by andersevenrud** [comment]
@khoaakt OS.js now supports running from file:// ;)

**Comment by khoaakt** [comment]
@andersevenrud,
Wait..., How about the "installer that runs in the browser"? Do you have planned yet?

**Comment by andersevenrud** [comment]
@khoaakt I will have a look at it, yes.

**Comment by andersevenrud** [comment]
Now I see... you tried to rename or move the file ?

**Comment by andersevenrud** [comment]
This is basically done :)

**Comment by karanganesan** [comment]
How can I build one ?
