### ISSUE TITLE
Support for other HTML5 apps (Firefox OS etc.)

### ISSUE THREAD

**Issue by khoaakt** [andersevenrud/OS.js-v2#97]
Can you port the HTML5 app into OS.js like Symbiose OS? not only that it can port the software running on Linux on the server and open it on the web os.

**Comment by andersevenrud** [comment]
You can already run Linux applications on OS.js with Broadway (#29).

But HTML5 applications should be pretty easy to get going. I'll have a look at it.

Thanks :)

**Comment by andersevenrud** [comment]
Done some research and it looks like Firefox Marketplace implementation should be pretty easy to do :)

That's pretty exciting, and I'll get right on doing some testing!

**Comment by khoaakt** [comment]
Good job, I expect that will have a right direction for os.js :)

**Comment by khoaakt** [comment]
Wait...
